- synth.metadata
- synth.py
Autosynth is changing config files that we needed to change for integration tests
> chore: ignore common kokoro config for setting test project

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ErrorCode.java
Adds a public method to get the gRPC status code from a `SpannerException`.
Fixes #14.
> feat: add public method to get gRPC status code

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Adds support for using CallCredentials that could vary per call instead of only static credentials passed in at startup.
Fixes #18
> feat: add support for CallCredentials

- google-cloud-spanner/pom.xml
See https://github.com/googleapis/java-cloud-bom/pull/241#issuecomment-573748218
> deps: mockito scope should be test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseNotFoundException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
DatabaseClients should not continue to try to send RPCs to a database that has been deleted. Instead, the session pool will keep track of whether a DatabaseNotFound error has been returned for a database, and if so, will invalidate itself. All subsequent calls for this database will return a DatabaseNotFoundException without calling a RPC.
If a database is re-created, the user must create a new DatabaseClient with a new session pool in order to resume usage of the database.
Fixes #16
> fix: stop sending RPCs to deleted database

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Session.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Sessions should be closed using an async gRPC call in order to speed up the closing of a large session pool. Instead of using its own executor, which is limited to 8 worker threads, to execute asynchronous delete session calls, the session pool should use the asynchronous call option in gRPC. This allows a larger number of asynchronous delete session calls to be executed in parallel and speeds up closing a session pool with a large number of sessions.
Testing against a real Cloud Spanner database with a session pool containing 1,000 sessions shows the following performance for closing the session pool:
Without this change (3 test runs):
6603ms
8169ms
8367ms
With this change (3 test runs):
1297ms
1710ms
1851ms
Fixes #19
> perf: close sessions async

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Session.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Reverts googleapis/java-spanner#24
The change continues to cause compatibility test failures.
> Revert "perf: close sessions async"

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
Fixes #21
The `registerSpanNamesForCollection()` method is deprecated since OpenCensus-`0.18` release, the alternative is `EndSpanOptions#getSampleToLocalSpanStore()`
See: https://github.com/census-instrumentation/opencensus-java/blob/2a17c8482ffb04540ea4ac0a5f746ad8d536c996/api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java#L102-L112
> chore: remove deprecated registration of the span names for zpages

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Session.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
We reverted #24 due to the binary compatibility test failure. This reverts #43 and adds:
- a config file to ignore the interface change to prevent future test failures.
- adds @InternalApi annotations to the updated interfaces.
Fixes #19
> perf: close sessions async revert revert

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
The ITClosedSessionTest could cause a flaky failure because it deletes sessions on the server and then repeatedly executes queries on the session until it returns a NOT_FOUND error. The actual deletion could however happen exactly at the moment that the test query was executed, which will cause Cloud Spanner to return a different error message than the standard 'Session not found' error message.
Fixes #41
> test: fix flaky integration test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
Any error that might occur during the listing of databases of an instance will now also include the name of the instance and the page token that was used to try to get the databases. This makes
it easier to debug why a particular RPC might have failed.
The flaky fails mentioned in #17 have not occurred for a while, and it is very well possible that this problem was a temporary backend problem. This extra information will make it easier to debug the failures should they occur again.
Closes #17
> info: add additional information to error message

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
This PR moves the custom `Backoff` functionality and settings from the `SpannerImpl` class to `AbstractResultSet`, as that is the only place where it is still in use.
The `Backoff` configuration was previously a hard coded value. It now uses the gapic configuration for streaming RPCs as the backoff is only used for the `ResumableStreamIterator` which is used by the `executeStreamingSql` and `streamingRead` RPCs.
Updates #20
> fix: use streaming retry settings for ResumableStreamIterator

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
Aborted read/write transactions used static retry settings that were not coming from the gapic configuration. This PR changes that to using the `default` retry settings from the gapic configuration. As the default retry settings themselves are not accessible from the generated `SpannerStubSettings` class, the retry settings are taken from the configuration of the `Rollback` RPC, which is also linked with the `default` retry settings.
Updates #20
> fix: use default retry settings for aborted transactions

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseNotFoundException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionNotFoundException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
Use the returned resource type instead of the error message to determine the type of error.
> fix: use resource type to identify type of error

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceNotFoundException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
The session pool should handle InstanceNotFound in the same way as DatabaseNotFound errors, i.e. stop sending RPCs and also consider an instance that has been re-created with the same name
as a different instance, and hence require the user to re-create any database client before it can be used again.
Fixes #60
> fix: stop sending RPCs on InstanceNotFound

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MetricRegistryTestUtils.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Updates #53 and continuation of #54
New Metric:
`cloud.google.com/java/spanner/get_sessions_timeout` => The number of get session timeouts due to pool exhaustion. This value is continuously increasing, so decided to use `Cumulative` (or `Counter`) type to record it.
> feat: add session timeout metric

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/FailOnOverkillTraceComponentImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TracerTest.java
> Fix: multiple calls to end of span

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
Updates #53 and continuation of #54 and #65.
New Metrics:
`cloud.google.com/java/spanner/num_acquired_sessions` => The number of sessions acquired from the session pool.
`cloud.google.com/java/spanner/num_released_sessions` => The number of sessions released (or destroyed) by the user and pool maintainer.
~Another option, instead of having two metrics what if we just include one metric `cloud.google.com/java/spanner/diff_acquired_released_sessions` to indicate diff/gaps between acquired and released sessions. I think stand alone they both (**num_acquired_sessions** and **num_released_sessions**) are adding very less value unless we combine them to see the session leaks or other anomalies.~
> feat: add metrics to capture acquired and released sessions data

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackendExhaustedTest.java
The `SessionPool` uses the same executor for both creating sessions and preparing these for read/write transactions. This could in very specific circumstances lead to thread starvation, which again can cause the session pool to stop returning sessions, even when there are sessions available in the pool.
> fix: prevent potential thread starvation in SessionPool

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Credentials should never be used in combination with plain text communication. Setting an emulator host should therefore also automatically override any credentials that may have been set.
> fix: never use credentials in combination with plain text

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
This PR adds an automatically generated identifier to all database clients that are created by the client library. This avoids collisions of the same metrics being registered multiple times, and makes it possible to distinguish different clients from each other in the monitoring.
This PR does not allow the user to specify the id, but this could be added in a future change. That would need an API change by adding an overload to the method `getDatabaseClient(DatabaseId)` with an additional `clientId` parameter.
This should also fix the build error in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2323.
Fixes #106
> fix: add client id to metrics to avoid collisions

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
Retry the restore operation in the integration test if the restore is blocked by another pending restore operation. Wait 1 minute between each retry, and retry at most 10 times. After that, the test will be
skipped.
Fixes #118
> fix: retry restore if blocked by pending restore

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
> tests: assign unique id's per test case

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolBenchmark.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
When more sessions are requested by the user application than are available in the session pool,
the session pool will now create new sessions in batches instead of in steps of 1. This reduces
the number of RPCs needed to serve a burst of requests. The default step size is 25 sessions.
In a default setup with `MinSessions=100, MaxSessions=400, NumChannels=4` a session pool that receives a burst of read or write requests will now have to execute 16 `BatchCreateSessions` RPCs as opposed to 304 `BatchCreateSessions` RPCs when using steps of 1.
A benchmark for the session pool has also been added to be able to compare performance and the
number of RPCs needed before and after this change. This benchmark can also be used for future
changes to verify that the change does not deteriorate …
> perf: increase sessions in the pool in batches

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
RPCs returning a long-running operation, such as CreateDatabase, CreateBackup and RestoreDatabase, are non-idempotent and cannot be retried automatically by gax. This means that these RPCs sometimes fail with transient errors, such as `UNAVAILABLE` or `DEADLINE_EXCEEDED`. This change introduces automatic retries of these RPCs using the following logic:
1. Execute the RPC and wait for the operation to be returned.
2. If a transient error occurs while waiting for the operation, the client library queries the backend for the corresponding operation. If the operation is found, the resumes the tracking of the existing operation and returns that to the user.
3. If no corresponding operation is found in step 2, the client library retries the RPC from step 1.
Fixes …
> fix: retry non-idempotent long-running RPCs

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
The test should check for at most baseThreadCount instead of equality, as it is possible that the thread pool shuts down one or more of its threads temporarily.
Fixes #146
> fix: fix flaky test and remove warnings

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolBenchmark.java
The `steadyIncrease` benchmark only checked out a read-only session from the pool, but did not actually start the transaction. That is only done once a statement is issued for the transaction.
Note that issuing the statement does not actually execute the statement. That is deferred to the first call to `ResultSet#next()`.
This keeps the benchmark in sync with the version for the Go client and makes the results from the two comparable with each other.
> tests: benchmark should start the transaction

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BackupId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceConfigId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
Check and report null input for the static create methods of the InstanceId, InstanceConfigId, DatabaseId, SessionId and BackupId classes.
Fixes #145
> fix: check for null input for Id classes

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
The flaky test failure was caused by a lower number of base threads being calculated before the test started, and not by an unexpected drop in the number of threads after the test. This is now mitigated by waiting for the initialization to finish before starting the test.
Fixes #146
> fix: wait for initialization to finish before test

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
The integration test environment tries to cancel the `CreateInstance` RPC, and otherwise tries to delete the instance, if the creation fails. This also adds the methods `getOperation` and `cancelOperation` to `InstanceAdminClient`. These had already been added to `DatabaseAdminClient`, but not to `InstanceAdminClient`.
Fixes #144
> fix: clean up test instance if creation failed

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Support more than one query hint in `StatementParser`.
Fixes #163
> fix: StatementParser did not accept multiple query hints

- .gitignore
- google-cloud-spanner/pom.xml
- grpc-google-cloud-spanner-admin-database-v1/pom.xml
- grpc-google-cloud-spanner-admin-instance-v1/pom.xml
- grpc-google-cloud-spanner-v1/pom.xml
- pom.xml
- proto-google-cloud-spanner-admin-database-v1/pom.xml
- proto-google-cloud-spanner-admin-instance-v1/pom.xml
- proto-google-cloud-spanner-v1/pom.xml
* imports `com.google.cloud:google-cloud-shared-dependencies` to manage all common dependency versions for `google-cloud-*` clients
* this should reduce the noise from renovate PRs as we can group multiple dependency updates in a single google-cloud-shared-dependencies update
* this means we're actually version managing more dependencies than previously
* introduces the flatten-maven-plugin which will "flatten" the pom and resolve all dependency versions including transitive ones. Below is an example of the flattened `pom.xml` that will be installed. It should resolve to the the same set of dependencies as if it were not flattened.
<details>
<summary>Flattened pom.xml</summary>
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 …
```
> feat(deps): import shared-dependencies bom and use maven-flatten-plugin

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
> fix: create filter in correct order

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Most errors that occur during preparing a session for a read/write transaction should be considered permanent, and should stop the automatic preparing of sessions. Any subsequent call to get a read/write session will cause an in-process BeginTransaction RPC to be executed. If the problem has been fixed in the meantime, the RPC will succeed and the automatic prepare of sessions will start again. Otherwise, the error is propagated to the user.
Fixes #177
> fix: stop preparing session on most errors

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
* Removes specific error message checking, as the backend may change these without prior notice.
* Removes warnings regarding deprected ExpectedException class.
* Refactored to reuse the same table for most tests to reduce execution time.
Fixes #175
> fix: remove error message checking

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
The `ITBackup` test fails randomly (and lately: consistently) on the CI environment with timeout errors. This seems to be caused by several backup operations that are still in progress and do not finish. Cancelling these before starting the actual backup tests seems to solve the problem (for now).
> tests: Attempt to fix random timeouts in ITBackup

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Currently `restoreDatabase`, `updateBackup` and `deleteBackup` are final methods. For some internal tests, we need to override these methods so ideally they shouldn't be final.
> fix: make it possible to override backups methods

- samples/install-without-bom/pom.xml
This should fix the broken samples builds.
> chore: bump Spanner version for samples without bom

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
SpannerRetryHelperTest.testExceptionWithRetryInfo could sometimes fail on some environments. I have not been able to reproduce it locally, but one possible reason for the failure could be truncation when converting from nanoseconds to milliseconds. Now both the timeout and the verification use nanosecond precision.
This change also removes all uses of hamcrest in this test file.
Fixes #200
> fix: use nanos to prevent truncation errors

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolIntegrationTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Closing a Spanner client means that all resources that have been returned by the client are no longer valid, including all DatabaseClients and corresponding session pools. This will cause errors for any other process that might still want to use these resources. This change marks when and by which call stack a Spanner client is closed, and includes that in any subsequent IllegalStateException that is returned to any process that tries to use the resources that have been returned by the Spanner client. This makes it easier to track down where and when a Spanner client is closed by accident.
> feat: mark when a Spanner client is closed

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Setting a timeout value for Partitioned DML would not be respected if the timeout value was higher than the timeout value set for the ExecuteSql RPC on the SpannerStub. Lower timeout values would be respected.
Fixes #199
> fix: Partitioned DML timeout was not always respected

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
The PartitionedDML stub was not closed when Spanner was closed.
In addition, Spanner did not wait for the channels to actually close, causing some test cases to (sometimes) log a warning that the channel had not been closed.
> fix: partitionedDml stub was not closed

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
The PartitionedDML retry settings were only applied for the RPC, and not for the generic retryer that would retry the PDML transaction if it was aborted by Spanner. This could cause long-running PDML transactions to fail with an Aborted exception.
Fixes #199
> fix: PDML retry settings were not applied for aborted tx

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Some tests relied on an environment variable having been set for a default project id credentials file. This change removes this dependency by setting an explicit project id and credentials instance.
Fixes the build error in #218 
Towards #219
> fix: remove the need for any env var in all tests

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
> tests: add additional tests for client ids

- .kokoro/build.sh
- .kokoro/presubmit/lint.cfg
- google-cloud-spanner-bom/pom.xml
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
- grpc-google-cloud-spanner-admin-database-v1/pom.xml
- grpc-google-cloud-spanner-admin-instance-v1/pom.xml
- grpc-google-cloud-spanner-v1/pom.xml
- pom.xml
- samples/install-without-bom/pom.xml
- samples/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
> fix: backend now supports optimizer version for DML

- google-cloud-spanner-bom/pom.xml
Including the google-cloud-spanner test-jar in the bom will allow other libraries to use the test jar without having to specify a version. This again should prevent the kind of failures that we are currently seeing in https://github.com/googleapis/java-spanner-jdbc/pull/142
(The jdbc driver currently defines a specific version for the test-jar in the pom [here](https://github.com/googleapis/java-spanner-jdbc/blob/bc7d5bd6205b23c99d01d2895ffb5c48ba423ea3/pom.xml#L62).)
> deps: include test-jar in bom

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MetricRegistryTestUtils.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Updates #53, this is based on the last discussion in the thread: https://github.com/googleapis/java-spanner/issues/53#issuecomment-601455550
This is how it looks in Stackdriver UI:
**Breaking Note:**
The `cloud.google.com/java/spanner/in_use_sessions` metric has been deprecated since v1.55.2, use `cloud.google.com/java/spanner/num_sessions_in_pool` instead.
> feat: add num_sessions_in_pool metric

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Use milliseconds instead of nanoseconds as unit to prevent rounding errors to cause test failures.
Fixes #257
> fix: use millis to prevent rounding errors

- google-cloud-spanner-bom/pom.xml
- google-cloud-spanner/pom.xml
- grpc-google-cloud-spanner-v1/pom.xml
The Maven flatten plugin transforms the pom of the project from a set of imports and transitive dependencies into a pom that contains all dependencies and versions explicitly. This process did however miss the javax-annotations-api dependency that is only included for JDK9 and higher.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3139
> fix: include an explicit version for javax-annotations-api

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
The test case SessionPoolTest.testMaintainerKeepsWriteProportion could fail as it queried the session pool for the number of write sessions by doing two calls; one for available write sessions and one for sessions being prepared. If one of the sessions that was being prepared was returned to the pool between the two calls, the test case would fail because it calculated the wrong number.
Fixes #264
> test: get write sessions in one call

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
The `SpannerRetryHelperTest.testExceptionWithRetryInfo` could still fail on Windows. Some more digging seems to indicate that this is a known bug in the accuracy of the `Thread.sleep(long)` method on Windows.
See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6435126 and https://stackoverflow.com/questions/824110/accurate-sleep-for-java-on-windows
Fixes #257
> test: try to workaround sleep bug in windows

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsThreadTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- grpc-google-cloud-spanner-v1/pom.xml
- pom.xml
> feat(deps): adopt flatten plugin and google-cloud-shared-dependencies and update ExecutorProvider

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
Increase length of debug string to 36, due to UUID length. According to https://tools.ietf.org/html/rfc4122#section-3 a UUID should be represented as 36 characters (32 hex digits + 4 dashes) in string format. This makes it more convenient for debugging purposes.
Fixes #300
> feat: increase the max length of debug string

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
The abstract base class for all Connection API integration tests were marked with category IntegrationTest, while all concrete subclasses were marked with ParallelIntegrationTest. This caused them to be excluded from the CI builds.
> tests: enable Connection API ITs

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/EncodingInterceptor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsThreadTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
Adds support for setting the compressor to use for gRPC calls.
> feat: support setting compression option

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
Include default fallback values in case the retry settings are removed or set to values that are invalid (i.e. 0).
> fix: set default values for streaming retry

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadWriteAutocommitSpannerTest.java
Skip autocommit timeout test on emulator because of this: https://github.com/googleapis/java-spanner/pull/319#issuecomment-654682576
> test: skip autocommit timeout test on emulator

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
If an AsyncResultSet was paused directly after receiving its last row and then cancelled while in paused mode, there was a small chance that the callback would not be called a last time to indicate to the user that the result set had been cancelled.
Updates #327
> test: fix potential race condition in Async ResultSet

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Fixes the retry/timeout config assertion tests in SpannerOptionsTest to align with the changes introduced by switching to the grpc_service_config for generation.
Note: This PR is based on and will be pulled into the `autosynth-googleapis` regen branch.
cc: @hengfengli @olavloite @skuruppu
> fix: apply SpannerOptionsTest patch

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
The gRPC keep-alive was set to 120,000 seconds instead of 120 seconds.
> fix: set gRPC keep-alive to 120 seconds

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
A transaction could in some circumstances be retried after an abort using the previous transaction id. This would cause the retry to abort directly as well, and then start a new transaction. This extra loop has now been removed.
Fixes #327
> fix: fix potential unnecessary transaction retry

- .kokoro/continuous/samples/common.cfg
- .kokoro/continuous/samples/samples-java11.cfg
- .kokoro/continuous/samples/samples-java8.cfg
- .kokoro/nightly/samples/common.cfg
- .kokoro/nightly/samples/samples-java11.cfg
- .kokoro/nightly/samples/samples-java8.cfg
- .kokoro/presubmit/samples/common.cfg
- .kokoro/presubmit/samples/samples-java11.cfg
- .kokoro/presubmit/samples/samples-java8.cfg
Adds configuration files in kokoro to run sample tests in java 8 and java 11. These were added in the continuous, nightly and presubmit builds.
This PR adds new `cfg` files for running the tests while not removing the existing sample tests (so that the build succeeds). 
When we switch over to the new `cfg` files for the sample tests, we can remove the old ones.
Fixes #280 and #283
> fix: runs sample tests in java 8 and java 11

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Check whether the emulator is actually running if the environment variable has been set to localhost.
Fixes #326
> fix: check if emulator is running if env var is set

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionRetryTest.java
> test: fix flaky ITTransactionRetryTest

- .kokoro/continuous/java11-samples.cfg
- .kokoro/continuous/java8-samples.cfg
- .kokoro/continuous/samples/samples-java11.cfg
- .kokoro/continuous/samples/samples-java8.cfg
- .kokoro/nightly/java11-samples.cfg
- .kokoro/nightly/java8-samples.cfg
- .kokoro/nightly/samples/samples-java11.cfg
- .kokoro/nightly/samples/samples-java8.cfg
- .kokoro/presubmit/java11-samples.cfg
- .kokoro/presubmit/java8-samples.cfg
- .kokoro/presubmit/samples/samples-java11.cfg
- .kokoro/presubmit/samples/samples-java8.cfg
This PR renames the java specific sample config files for kokoro, so that they are the same as it is done in the BigQuery java client. The filename pattern is: java<version>-samples.cfg (see examples here https://github.com/googleapis/java-bigquery/tree/master/.kokoro/nightly).
Fixes #280 and #283
> refactor: normalises samples config names

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
@thiagotnunes Would you mind trying the same test with this PR? I don't have a dataset that is big enough that it will run for more than one hour.
Fixes #336
> fix: respect PDML timeout when using streaming RPC

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ITSessionPoolIntegrationTest.java
Rename the SessionPoolIntegrationTest to IT... so it is actually picked up by the configuration that executes the integration tests.
> test: rename integration test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Include the SQL statement in the error message when a query fails. By default it does not contain the parameter values of the SQL statement to prevent potentially sensitive information from being logged. The parameter values can be included in the error message by setting the log level for `GrpcStreamIterator` to at least `FINEST`.
Fixes #278
> feat: include SQL statement in error message

- renovate.json
The updated library only support Java 9+ but we still support Java 7 and
8. We want to stop renovate bot from asking us to update this
dependency.
Updates #258
> deps: stop auto updates of commons-lang3

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
Removes buganizer comments from recently created predicate classes.
These URLs are not accessible externally.
> cleanup: removes unnecessary comments

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Skip GapicSpannerRpcTest when an emulator host has been set, as the test interferes with the check whether the emulator is running.
> test: skip test on emulator

- CONTRIBUTING.md
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
The emulator uses the project id in order to list the instance configurations. If the none is set, it uses the project set through the `gcloud` tool, which might mismatch the project being used to create the databases in the integration tests.
Here, I explicitly set the project id to be the same as the one being used to create the databases for the integration tests.
> fix: sets the project for the integration tests

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
The Spanner client allows a user to set custom timeouts while creating a SpannerOptions instance, but these timeouts are static and are applied to all invocations of the RPCs. This change introduces the possibility to set custom timeouts and other call options on a per-RPC basis.
This feature will also be very useful for the Async Connection API, as it will allow applying the statement timeouts for async calls on a per RPC-invocation basis.
Fixes #378
> feat: support setting timeout per RPC

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
The automatic retryer for non-idempotent administrative requests did not keep track of the nextPageToken correctly when querying the backend for running operations. This could cause an infinite loop if a resource (database/backup) with the same name had been created repeatedly on the same instance.
> fix: remove potential infinite loop in administrative requests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Iterating over an AsyncResultSet using a standard `while (rs.next())` loop would fail after the last row was consumed.
> fix: iterate over async result set in sync

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
Previously DirectPath was enabled by an environment variable. Now since gax-java [v1.57.0](https://github.com/googleapis/gax-java/releases/tag/v1.57.0) DirectPath can be enabled by using `InstantiatingGrpcChannelProvider.Builder.setAttemptDirectPath(true)`.
Some changes are temporary and will be removed once DirectPath goes public using the default spanner endpoint. For now we want to be able to test the DirectPath-enabled endpoint with different client scenarios:
- Client is running on a ipv4-only VM
- Client is running on a ipv6-enabled VM
- Client fallbacks to use normal CFE path
For the purpose of our internal E2E tests, I added a test profile called `spanner-directpath-it` which introduces two new sys props:
- `spanner.attempt_directpath`: this defines whether the test client would …
> feat: Add experimental DirectPath support

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingAsyncResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadAsyncTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncExamplesTest.java
Replace com.google.common.collect.ImmutableList
with java.util.List
Fixes #410 ☕️
> Remove Guava ImmutableList from API surface.

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
If a transaction is aborted before a `batchUpdateAsync` call, the RPC will return an `Aborted` status. This status was not translated to a `com.google.cloud.spanner.AbortedException`, but was instead returned as a `com.google.api.gax.rpc.AbortedException`, which could cause retry handling to fail.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3634
> fix: fix aborted handling of batchUpdateAsync

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Internally, we are using version 1.47.1 of the gax-grpc library, which does not provide a method currently being used (setExecutor).
In here we use a method that is available in 1.47.1 and achieves the same goal (setExecutorProvider).
> fix: uses old version of gax-grpc method

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractLazyInitializer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/LazySpannerInitializer.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/LazySpannerInitializerTest.java
Adds a `LazyInitializer` for `Spanner` instances that can be used in environments where it is desirable to initialize one instance once, and reuse this for multiple purposes, such as for example Google Cloud Functions.
This change would allow us to simplify the [Google Cloud Functions Java sample](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/spanner/src/main/java/functions/HelloSpanner.java).
Towards https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2862.
> feat: add lazy initializer

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
`AsyncResultSetImpl` should not close its delegate `ResultSet` in the `CallbackRunnable`, but should leave that to the `ProduceRowsCallable` and instead only set the flag `cursorReturnedDoneOrException`. Otherwise, the main loop that fetches and produces rows could get stuck in an infinite loop.
> fix: do not close delegate rs in callback runnable

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
We had removed a method from GapicSpannerRpc that was used in the internal testing infrastructure. We are adding this back for the time being.
> fix: re-adds method used in internal testing

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
Adds additional checks on `NUMERIC` values before sending them to Cloud Spanner in order to return sensible error messages as soon as possible, and adds documentation on how to handle `NUMERIC` values with trailing zeros in the fractional part.
> fix: improve numeric range checks

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
The `SpannerPool` uses among other fields the `credentials` of a `ConnectionOptions` to determine whether an existing `Spanner` instance can be reused or not. Certain credentials instances, most notably `UserCredentials`, are mutable and the result of `equals(Object)` and `hashCode()` of an instance may change during its lifetime. This could cause the `SpannerPool` to inadvertently close a `Spanner` instance that is still in use.
This change replaces the usage of the actual credentials as part of the pool key with a key that is based on the method that was used to determine the credentials. This ensures that if two connections request a `Spanner` instance using the same `credentialsUrl`, that they will be considered equal. The same also applies to two connections that both do not set any …
> fix: use credentials key in pool

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
Restore/Backup operations filtering broken, skipping the tests that use it for now.
> fix: skip failing backup tests for now

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
If a client application requested a session from the session pool, and that request required a new BatchCreateSessions request that would fail, then the error from the BatchCreateSessions RPC would be propagated to both the ReadContext#executeQuery(..) method as well as the ResultSet#close() method. The latter should not happen, as the close method should silently ignore any errors from the session creation.
> fix: ResultSet#close() should not throw exceptions from session creation

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractLazyInitializer.java
Increases the visibility of `AbstractLazyInitializer#get()` to make it usable outside the client library.
Replaces #461.
> fix: increase visibility of #get()

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
Shutdown the executor that maintains the pool when the pool is closing.
> fix: close executor when closing pool

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
AsyncTransctionManager should rollback the transaction if close is called while the transaction is still in state STARTED. Failing to do so, will keep the transaction open on the backend for longer than necessary, holding on to locks until it is garbage collected after 10 seconds.
Fixes #504
> fix: AsyncTransactionManager should rollback on close

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContextFutureImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
Invalid statements or other statements that would cause an error would not cause the returned ApiFuture to fail.
Fixes #514
> fix: AsyncTransactionManager did not propagate statement errors

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
Adds NUMERIC, TIMESTAMP and DATE types to the javadocs of the Key class.
> fix: fixes javadocs for Key

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractLazyInitializer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/LazySpannerInitializer.java
The `AbstractLazyInitializer#initialize()` method should be `protected`.
> fix!: initialize should be protected

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
> test: remove explicit CreateInstance timeout

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/CommitResponse.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/WriteResponse.java
Adds the possibility of adding options to the write operations and encapsulates the write response into its own class so that we can augment the response with more fields than the commit timestamp.
At the moment, the new methods just delegate to the existing write methods. Once we add write option implementations we should change the definition of the added methods.
> feat: adds options to the write operations

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
Adds tests for `SessionNotFound` exceptions for `AsyncRunner` and removes some warnings regarding deprecated methods and possible resource leaks.
> test: add tests for session not found retries for async runner

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
`SessionNotFoundException` was not retried if these happened when using `AsyncTransactionManager`. These exceptions are now handled explicitly in the following way:
1. The underlying session that is used for the transaction is replaced with a new session from the pool.
1. The `SessionNotFoundException` is translated to an `AbortedException`, which again will be retried, assuming that the client application has implemented a normal retry loop, as is required when using an `AsyncTransactionManager`.
> fix: SessionNotFound was not retried for AsyncTransactionManager

- samples/snippets/assembly-descriptor.xml
- samples/snippets/pom.xml
Creates a jar with dependencies for the snippets samples. This is how we executed the samples in the other repository, so we are mimicking the process here.
> fix: adds assembly descriptor to snippets samples

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
The test wrongly assumed that if the previous page returned a `nextPageToken` that the next call would always contain exactly one more result. It is however possible that the result that had not yet been returned was deleted by another process in the meantime, which would cause the next page to be empty.
Fixes #570
> test: check that page actually contains an element

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AutocommitDmlMode.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/TransactionMode.java
Some enums were defined as package-private, but these were used in the public API of the Connection API. That made the specific methods in the Connection API unusable from outside the Spanner client library.
Towards https://github.com/googleapis/java-spanner-jdbc/issues/253
> fix: make enums in the Connection API public

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
Adds descriptions for the supported connection URL properties. These can be picked up by the JDBC driver and shown as descriptions for java.sql.DriverPropertyInfo.
> docs: add descriptions for connection URL properties

- google-cloud-spanner/pom.xml
Adds a profile for regenerating the SQL test files for the Connection API. This was forgotten when moving the Connection API code from the jdbc repository to the client library repository.
> test: add profile for generating test sql scripts

- .github/CODEOWNERS
Adds api spanner java team as samples code owners
> fix: adds api spanner team as samples code owners

- .kokoro/nightly/java11-samples.cfg
- .kokoro/nightly/java8-samples.cfg
- .kokoro/nightly/samples.cfg
- .kokoro/presubmit/java11-samples.cfg
- .kokoro/presubmit/java8-samples.cfg
- .kokoro/presubmit/samples.cfg
- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
- samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java
- synth.py
Updates the project and instance for the samples tests, so that they use the same configuration as the integration tests.
Fixes #606
> fix: updates project / instance for samples tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContextFutureImpl.java
A "Session not found" when using an AsyncTransactionManager could cause an infinite wait for an `ApiFuture` that would never be done.
Fixes #605
> fix: session retry could cause infinite wait

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
These tests were previously disabled due to a bug in production, which has been fixed.
> Revert "fix: skip failing backup tests for now"

- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Delete stale sample databases. This is the same change as in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4133.
Fixes #585
> fix: delete stale sample databases

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
If the first statement of a read/write transaction was a query or a read operation, and the application would not call `ResultSet#next()` on the return result, the transaction would hang indefinitely as the query would be marked as the one that should initiate the transaction (inline the `BeginTransaction` option). The query would however never be executed, as the actual query execution is deferred until the first call to `ResultSet#next()`.
Fixes #641
> fix: query could hang transaction if ResultSet#next() is not called

- synth.py
Prevents the re-generation of the github CODEOWNERS file, since we have updated the owners for the samples directory.
> fix: does not generate codeowners

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
The query_ThenUpdate_ThenConsumeResultSet did not take into account that the session pool initialization will execute 4 BatchCreateSessions requests. These will normally be executed before the test transaction, but sometimes at least one of those requests might arrive after the transaction has started. That could cause the last 3 requests on the mock server to be
different from what the test expected.
> test: fix flaky InlineBeginTransactionTest

- CHANGELOG.md
Fixes the changelog for version 2.0.0
> fix: fixes changelog for upgrade 2.0.0

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AdminRequestsPerMinuteExceededException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Automatically retry requests that fail because the admin requests per seconds limit has been exceeded using an exponential backoff.
Fixes #655 and others
> feat: retry admin request limit exceeded error

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
Some applications automatically add additional properties to connection strings that are unknown to the Spanner Connection API (and thereby also the Spanner JDBC driver). This causes the connection attempt to fail. This change allows a user to specify 'lenient' mode where unknown properties only generate a warning instead of an error.
Needed for https://github.com/dropwizard/dropwizard/issues/3461
Needed for https://github.com/googleapis/google-cloud-java/issues/6671
Needed for https://github.com/googleapis/java-spanner-jdbc/issues/283
> feat: allow lenient mode for connection properties

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDirectPathFallback.java
Add a DirectPath fallback test for spanner. The test is basically the same as what we have for bigtable (https://github.com/googleapis/java-bigtable/blob/master/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/it/DirectPathFallbackIT.java). The logic of the test is:
1. First wait until DirectPath traffic is observed;
2. Blackhole DirectPath ipv4 and ipv6 IP, and wait until the client fallback to use CFE;
3. Unblackhole DirectPath ipv4 and ipv6 traffic, and the client should upgrade back to use DirectPath again.
The DirectPath and CFE traffic are distinguished by peer IP.
> chore: add DirectPath fallback integration test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/FailedBatchUpdate.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/FailedQuery.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/FailedUpdate.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbortedTest.java
Transaction retries in the Connection API / JDBC driver could fail if the following happened:
1. The initial transaction contains a statement that returns an error that does not invalidate
the transaction, such as for example a "Table not found" error, and that error is caught and
handled by the application code.
2. The retry attempt tries to execute the failed statement to verify that the statement still
returns the same error. If however the transaction that is used by the retry has been aborted
immediately before the execution of this statement, the statement will now return Aborted
instead of the original error. That would be seen as a different error than the initial
error and would fail the retry attempt.
When the above happens, the Aborted error in the retry should be propagated …
> fix: transaction retry could fail if tx contained failed statements

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerAsyncTest.java
The ITTransactionManagerAsyncTest had a couple of problems:
1. The Spanner client was closed after each test, which would make only the first test to succeed.
1. The test class was not tagged with a category, which meant that it would not be executed by the CI builds. That is also the reason that the problem in 1 was not noticed.
Replaces #693
> test: fix ITTransactionManagerAsyncTest

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
- samples/snippets/src/test/java/com/example/spanner/AsyncExamplesIT.java
- samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
This change reduces the number of administrative requests that are executed by the samples integration tests, in order to prevent (or at least reduce) `RESOURCE_EXHAUSTED` errors caused by exceeding the [administrative requests limit](https://cloud.google.com/spanner/quotas#administrative_limits).
> test: reduce administrative calls in samples

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementTimeoutTest.java
The `StatementTimeoutTest.testTimeoutExceptionReadWriteTransactionMultipleStatements` had become flaky because of a combination of two other changes:
1. The first statement of a read/write transaction now includes a `BeginTransaction` option. If that statement fails with an error, the entire transaction will be retried, but then with an explicit `BeginTransaction` RPC. The latter is done to ensure that the statement that returned an error will be included in the transaction.
1. The Connection API did not correctly handle a situation where a statement first returned an error unequal to `Aborted`, and then during a retry would return `Aborted`.
The combination of the two above changes means that the first statement of a transaction can take longer than expected when it returns an error, as …
> test: increase timeout to prevent flakiness

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDmlTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Adds TransactionOptions and UpdateOptions for read/write transactions and statements. These can be used in the future to specify options to affect how transactions and statements will be executed.
These changes can be used as the basis for #676 and #576 to ensure both changes use the same approach, and to prevent enormous merge conflicts.
> feat: introduce TransactionOptions and UpdateOptions

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
These samples' region tags slightly differ from identical snippets in different languages. The following is the remedy:
1. Merge this PR to fix GitHub source (keep old tag for now)
2. Fix doc code includes to represent the better region tag
3. Submit a second PR to clean-up redundant region tag wrapping
> docs: homogenize region tags

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GrpcDatabaseAdminStubWithCustomCallableFactory.java
Reduces the probability of `RESOURCE_EXHAUSTED` errors during tests by making the GetOperation method retry errors with this code with an exponential backoff. The GetOperation method is called repeatedly for long-running operations by a polling future. These calls also count towards the max 5 admin requests per second.
Fixes #733
> fix: reduce the probability of RESOURCE_EXHAUSTED errors during tests

- samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java
> test: sample test did not wait for database creation to finish

- google-cloud-spanner/pom.xml
Adding `grpc-alts` as a runtime dependency causes the `maven-flatten-plugin` to add the compile time dependencies in the flattened pom. As far as I can tell, `grpc-alts` is (currently) only used for testing, so adding it as a `test` scoped dependency seems to make more sense to me.
Fixes the build error in https://github.com/googleapis/java-spanner-jdbc/pull/293
> deps: grpc-alts is only used for tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Adds an option to track the statement that starts a read/write transaction by inlining a `BeginTransaction` option with the request. This can be used to track down statements that do not return a transaction id in a timely fashon.
> test: add option to track the statement that starts a transaction

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
This is the final clean-up from https://github.com/googleapis/java-spanner/pull/752. New tagging is now live in docs.
> docs: cleanup inner region tags

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Instead of throwing an ALREADY_EXISTS error on the update database ddl operation, we resume the original operation. This is necessary, because the update database ddl is retryable. Because of this, we don't want to confuse the caller by bubbling up an ALREADY_EXISTS error on a retry, even though they used a non-existing operation id.
> docs: documents resume on update database ddl

- google-cloud-spanner/pom.xml
This reverts commit c8ef46f2637b58cc71d023764cdc11a7414d855f.
Without having grpc-alts in `runtime` / `compile` scope I get the following error when running the client library:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/alts/ComputeEngineChannelBuilder
at com.google.cloud.spanner.v1.stub.SpannerStubSettings.defaultGrpcTransportProviderBuilder(SpannerStubSettings.java:304)
at com.google.cloud.spanner.v1.stub.SpannerStubSettings.defaultTransportChannelProvider(SpannerStubSettings.java:309)
at com.google.cloud.spanner.v1.stub.SpannerStubSettings$Builder.createDefault(SpannerStubSettings.java:531)
at com.google.cloud.spanner.v1.stub.SpannerStubSettings$Builder.access$100(SpannerStubSettings.java:356)
at com.google.cloud.spanner.v1.stub.SpannerStubSettings.newBuilder …
```
> fix: grpc-alts is used not only in tests

- samples/snippets/src/main/java/com/example/spanner/StatementTimeoutExample.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Adds a sample for setting a timeout for a single RPC.
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3805
> docs: add sample for timeout for one RPC

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
If a query requests the begin of a new transaction, the transaction id is returned by the first call to `ResultSet#next()`. If the `ResultSet` is closed by another thread before the first result has been returned, or before that result has been consumed internally to set the transaction id, no transaction id will be set. This will cause any subsequent statement in the same transaction
to timeout while waiting for a transaction to be returned.
> fix: mark transaction as invalid if no tx is returned before close

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
Adding the same time series multiple times will cause an error in OpenCensus. A time series could be added multiple times for the same Database client id if a database client was invalidated, for example because if was created for a database that did
not exist.
This works for OpenCensusImpl 0.26 but not for 0.24, but that seems to be the case both with and without this change. With this change the problem is solved for 0.26. In version 0.24 OpenCensusImpl will always throw an error if you try to add a metric with the same name twice.
Fixes #202
> fix: remove time series before adding it

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
The keepAlive traces were being tracked along with the parent span set by the client, which clutters the tracing stack. Here, we set the tracing to blank before issuing the keepAlive query.
> fix: blanks span for session keepAlive traces

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
Adds a number of safeguards against hanging transactions if the first statement of a transaction for whatever reason fails to return a transaction ID, or otherwise returns an unexpected error. This PR contains the following safeguards:
1. If a statement requested a new transaction from Cloud Spanner and receives a response without a transaction ID, the statement will throw an exception. This should theoretically never happen. If it did happen, it would cause the second statement in the transaction to be 'stuck', as it would wait indefinitely for the first statement to return a transaction.
2. If the first statement of a transaction throws an unexpected error (a `Throwable` that is  not a `SpannerException`), the exception will be translated to a `SpannerException` and handled as such. …
> fix: safeguard against statement errors when requesting a transaction

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
If the first query or read operation of a read/write transaction would return `UNAVAILABLE` for the first element of the result stream, the transaction could get stuck. This was caused by the internal retry mechanism that would wait for the initial attempt to return a transaction, which was never returned as the `UNAVAILABLE` exception was internally handled by the result stream
iterator.
Fixes #799
> fix: UNAVAILABLE error on first query could cause transaction to get stuck

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
When the session pool is marked as invalid, we immediately close the pool maintainer in order to keep it from trying to replenish the pool. This way we prevent useless batch create sessions requests.
Fixes #768
> fix: closes pool maintainer on invalidation

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
The DatabaseClientImpl#singleUseBoundAsync is sometimes getting stuck during the execution. This is simple to reproduce by executing the test class multiple times.
This is due to the static single threaded executor that is shared among all the test cases.
In this fix, we create an executor in the setup method, avoiding the sharing of the same among different tests.
> test: fixes DatabaseClientImpl stuck test

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- synth.py
This should enable release-please on the 3.1.x branch
> build: add 3.1.x branch as protected and releasable

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Allows min/max sessions for the backing `SessionPool` to be specified in the connection URL.
Towards https://github.com/googleapis/java-spanner-jdbc/issues/334
> feat: allow session pool settings in connection url

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplStressTest.java
Reduces the number of test runs for `AsyncResultSetImplStressTest` to improve build/test time (reduces total build time with approx 10 seconds). The class has been stable for quite some time, so reducing the number of test runs should be safe.
> test: reduce number of stress test runs

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
* Unflakes `InlineBeginTransactionTest.testCloseResultSetWhileRequestInFlight`
* Refactors `InlineBeginTransactionTest` so that only those tests that require an executor are parameterized. This prevents a lot of tests from being executed 3 times without any difference between each test run.
* Reduces wait time while waiting for requests to be found on mock server to reduce build time.
> test: unflake testCloseResultSetWhileRequestInFlight

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackendExhaustedTest.java
The BackendExhaustedTest deliberately causes requests to get stuck on the mock server. This causes the Spanner instance to refuse to shutdown nicely and causes it to wait for 10 seconds. This can be circumvented by using shutdownNow() to force the closure of all gRPC transport channels. This reduces the overall build time with approx 10 seconds.
> test: reduce wait time for BackendExhaustedTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Suppress the logging of a warning to the console that a connection has been leaked, as that is exactly what the test is checking.
> test: suppress logging a known warning

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementNoParamExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementSetExecutor.java
Compiled client side statements should be immutable as they are only imported and compiled once.
> chore: make compiled statements immutable

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
Return the TransactionSelector that is built instead of falling through to the end of the method. The behavior does not change by this, but it makes it easier to read and understand the code.
Fixes #830
> cleanup: return instead of fallthrough + improve comment

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementExecutor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ForceCloseSpannerFunction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Adds the option to force-close `Spanner` instances for tests that execute long running statements that timeout. These would otherwise wait 10 seconds for the mock server to shutdown before finishing.
> test: force-close to speed up timeout tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
The keepAlive traces were being tracked along with the parent span set by the client, which clutters the tracing stack. Here, we set the tracing to blank before issuing the keepAlive query.
> fix(3.1.x): blanks span for session keepAlive traces

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
If the first query or read operation of a read/write transaction would return UNAVAILABLE for the first element of the result stream, the transaction could get stuck. This was caused by the internal retry mechanism that would wait for the initial attempt to return a transaction, which was never returned as the UNAVAILABLE exception was internally handled by the result stream iterator.
Fixes #799
> fix(3.1.x): UNAVAILABLE error on first query could cause transaction to get stuck

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
A bug was introduced, where if the caller tried to set a custom user agent with a header provider an exception would be thrown (for duplicate keys). Here, we merge the user agent set by the client along with the one set by the library, instead of throwing such exception.
Fixes https://github.com/googleapis/java-spanner/issues/880
> fix: allows user-agent header with header provider

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
This test was introduced in order to debug stuck transactions. The cause was unrelated though.
The test here is flaky, because there is a race condition between setting the stream field in the AbstractResultSet and checking it in the close method. Since the result set is not intended to be thread safe, we will not be synchronizing this variable.
More information can be seen in @olavloite 's investigation in: https://github.com/googleapis/java-spanner/issues/869#issuecomment-780476213
Fixes #869
> test: removes flaky close result set test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionAsyncApiAbortedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerAsyncTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
Both the documentation for `TransactionManager` as well as some internal retry loops wrongly used `SpannerException#getRetryDelayInMillis() / 1000` as input for `Thread.sleep(long)`. The retry delay is already in milliseconds and should not be modified.
Fixes #874
> fix: wrong use of getRetryDelayInMillis() / 1000 in documentation and retry loops

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
The `SpannerGapicRpcTest.testCustomUserAgent` test opened a new `Spanner` instance that was not closed after the test had finished. This would cause the threads that were used by that instance to remain active until the entire test run had finished. If this test happened to be executed before one of the tests that verify that all threads are closed when a `Spanner` instance is closed, the test would fail as it would detect the threads that were still active from the other test case.
Fixes #889
> test: close Spanner instance after test

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
We were not closing the spanner service instance after using it, causing threads not to be terminated. Here we make sure to close such service in a try with resources block.
Fixes #889
> test: fixes gapic spanner test

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
Instead of using the earliest version time of the database, uses the current time (from spanner). If we used the earliest version time of the database instead we would be creating an empty backup, since the database we are backing up is not 1 hour old (default version retention period).
> samples: PITR samples backup fix

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
Deprecates the `MaxIdleSessions` configuration option for the `SessionPool`. Users should instead set a higher value for `MinSessions` instead of using `MaxIdleSessions`. This will reduce both the complexity of session pool configuration and the session pool maintenance.
Fixes #865
> deprecation: deprecate MaxIdleSessions configuration option

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Adds client lib token for Liquibase.
Towards https://github.com/googleapis/java-spanner-jdbc/issues/297
> feat: add client lib token for Liquibase

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
Instead of hardcoding the version time in the create backup sample, parameterises it.
> samples: parameterises create backup version time

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
All throwables (and not just exceptions) should be ignored in the shutdown hook. Failing to close these resources during shutdown is not a major problem, as they will be garbage collected by the backend anyways. Without this wide catch, some
applications will log a ClassNotFoundException when shutting down, which can be confusing for end users.
Fixes #949
Also fixes https://github.com/cloudspannerecosystem/liquibase-spanner/issues/66#issuecomment-794765002
> fix: all throwables should be ignored in shutdown hook

- .github/release-please.yml
- .github/sync-repo-settings.yaml
Updates the github configuration to mark the branch 4.0.x as stable.
> chore: marks the branch 4.0.x as stable

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
Adds a non-blocking close method to `Connection` to support APIs that should offer only non-blocking methods to consumers (e.g. R2DBC).
The `Connection` interface is marked with `InternalApi` and documented with `Internal connection API for Google Cloud Spanner. This interface may introduce breaking changes without prior notice.` 
cc @elefeint
> feat!: add closeAsync() method to Connection

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
The backup pagination test should fail if the same page token is returned twice by the backend, instead of fetching the same page indefinitely. Further investigation is necessary if that actually happens, as it is not something that is expected.
> test: fail if the same token is seen twice

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
If the first statement of a read/write transaction fails with a `CANCELLED` error and the error message is `Read/query was cancelled due to the enclosing transaction being invalidated by a later transaction in the same session.`, then the transaction should be retried, as the error could be caused by a previous statement that was abandoned by the client but still executed by the backend. This could be the case if the statement timed out (on the client) or was cancelled.
Fixes #938
> fix: retry cancelled error on first statement in transaction

- samples/README.md
This will get the correct repo to clone, and instruct the user to switch directories to run commands, but I am not sure the fix is sufficient.
The samples (`SpannerSample.java`, `QuickstartSample.java`, `BatchSample.java`) use the default project, which seems to be unset when cloud shell opens. Perhaps they should be modified to take project ID as a runtime argument, too?
Fixes #1010
> Update cloudshell editor link and runtime directory

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Transactions that are retried because of an aborted transaction use the retry settings of the Rollback RPC. This ensures reasonable backoff values. It however also meant that transactions that are retried multiple times could exceed the total timeout of the retry settings, and that again would cause the Aborted error to propagate. This change sets the total timeout for transaction retries to 24 hours and disables any max attempts in the retry settings to prevent retries to fail because the deadline is exceeded.
Transactions can still fail with timeout errors if individual RPC invocations exceed the configured timeout of that RPC. This change only prevents timeouts from occurring because of repeated retries of an entire transaction.
Fixes #1008
> fix: transaction retries should not timeout

- .github/release-please.yml
- .github/sync-repo-settings.yaml
Sets branch 5.2.x as a protected branch. Configures CI and release please for such branch.
> chore: updates settings for 5.2.x branch

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/CredentialsService.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/LocalConnectionChecker.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
Improve error messages when something is wrong in the connection string.
Fixes https://github.com/googleapis/java-spanner-jdbc/issues/399
> docs: improve error messages

- .repo-metadata.json
This is used by autosynth to generate files such as the README.
> chore: sets the min version of the repo as Java 8

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/LocalConnectionChecker.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerTestUtil.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/LocalConnectionCheckerTest.java
Uses plain text, instead of ssl when testing for local connections. This fixes connection checks when using the `MockSpannerServiceImpl` and it works with the emulator as well.
Without this fix we would get a transport error when testing the `getConnection` when using the `MockSpannerServiceImpl`, since the client would expect `TLS`, while the server would be serving `plainText`.
> fix: plain text when testing emulator connection

- .github/workflows/ci.yaml
Linkage Monitor is intended to the latest libraries in the Libraries BOM. It does not work for the old version of the library.
> chore(ci): removing linkage monitor from 4.0.x branch

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Update StatementParser to include statement hints support for DML statements.
The Spanner JDBC driver would consider UPDATE statements that started with a statement hint as invalid statements. This change adds a check for statement hints at the beginning of a query, and accepts these as valid queries.
Fixes #1029 ☕️
> feat: Support query hints for DML statements

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/LocalConnectionChecker.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/LocalConnectionCheckerTest.java
The local connection checker should only check for unavailable exceptions when warning the user about the spanner emulator configuration. It should ignore all other kinds of errors.
> fix: local connection checker ignores exceptions

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunner.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackendExhaustedTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginBenchmark.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadWriteTransactionWithInlineBeginTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolBenchmark.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolMaintainerBenchmark.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
- samples/snippets/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
- samples/snippets/src/main/java/com/example/spanner/StatementTimeoutExample.java
Makes the `TransactionCallable` a `@FunctionalInterface` so it can be used with lambdas.
This PR also modifies all of its usages to the lambda syntax. Only syntatic changes were made, no logic changes were made here.
> feat: transaction callable as functional interface

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncRunner.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncAPITest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncExamplesTest.java
- samples/snippets/src/main/java/com/example/spanner/AsyncDmlExample.java
- samples/snippets/src/main/java/com/example/spanner/AsyncRunnerExample.java
Marks the async work interface as a functional interface.
This PR also modifies all of its usages to the lambda syntax. Only syntatic changes were made, no logic changes were made here.
> feat: async work as functional interface

- .github/blunderbuss.yml
- synth.py
> chore: add default assignee for issues

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
The check whether the previous statement timed out in the Connection API was
done when a statement was submitted to the connection, and not when the statement
was executed. That could cause a race condition, as statements are executed using
a separate thread, while submitting a statement is done using the main thread.
This could cause a statement to return an error with code ABORTED instead of
FAILED_PRECONDITION. A statement on a read/write transaction would always return
an error when a/the previous statement timed out, only the error code could
be different depending on whether the race condition occurred or not. This is
now fixed so that the error code is always FAILED_PRECONDITION and the error
indicates that a read/write transaction is no longer usable after a statement
timeout. …
> fix: check for timeout in connection after last statement finished

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
The comparison included the progress of the operation. If the operation is fetched twice, there is a (small) chance that the reported progress between the two will differ, but that should not cause the test to fail. This PR removes the progress field from the comparison.
Fixes #1033
> test: exclude progress from comparison

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITResultSetGetValue.java
Adds the method `getValue` to the `ResultSet`. This will return an encapsulated value. It supports all the column types that are provided.
> feat: adds getValue to ResultSet

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
SpannerImpl would keep a reference to all database clients that had been created and then invalidated because the database was deleted or did not exists in the first place. If the getDatabaseClient(String) method would be called multiple times for the same invalid database, the memory usage of the application would continue to increase.
Fixes #1089
> fix: do not keep references to invalidated clients

- samples/snippets/src/test/java/com/example/spanner/EncryptionKeyIT.java
- samples/snippets/src/test/java/com/example/spanner/SampleRunner.java
Retry backup operations during tests that fail because too many other backup operations are pending at that moment.
Fixes #1019
> test: retry backup operations on failure because of pending operations

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
Fix wrong Java docs for `Date` type.
Source: https://cloud.google.com/spanner/docs/data-definition-language#date
> docs: fix javadoc for Date type

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
A NullPointerException would be thrown when encoding the value to a proto if a Struct value was constructed with an Array field that contained at least one null value, and the type of the array field was boolArray, int64Array or float64Array.
Fixes #1106
> fix: prevent NPE in Struct with Array that contains null elements

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
Test to ensure the error in https://github.com/googleapis/java-spanner-jdbc/issues/444 is not present in the Java client library.
> test: add a test for selecting an array of structs

- samples/snippets/src/main/java/com/example/spanner/RestoreBackupWithEncryptionKey.java
The restore operation should use the default timeout of a restore operation. Although that timeout is long, the tests for the samples are only executed as part of the nightly build, which means that a long-running restore will not slow down PR builds.
Fixes #1019
> docs: use default timeout for restore operation

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Adding a custom user-agent was only possible by using an all lower-case key. A header key should however be case-insensitive. This PR changes the merging of a custom user-agent value with the default user-agent to use a case-insensitive comparison.
> fix: allow using case-insensitive user-agent key

- samples/snippets/src/main/java/com/example/spanner/CreateInstanceExample.java
The CreateInstance example opened a Spanner instance without closing it. That was spamming the test logs with a lot of the following warnings:
```
Apr 29, 2021 8:06:34 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=191, target=spanner.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChann …
```
> docs: close Spanner instance when it is no longer needed

- .github/release-please.yml
- .github/sync-repo-settings.yaml
Also removes clirr / linkage monitor from non master branches since they only work for the master branch.
> chore: adds branch 3.3.x as stable

- google-cloud-spanner/pom.xml
- samples/README.md
A custom `skipUTs` system property had been introduced to skip unit tests for the Spanner client library. None of the automated build scripts use this variable however, and instead use the standard `skipTests` variable. This caused all unit tests to be executed twice in the build scripts, which again could cause timeout errors, especially for the Windows builds.
Note: The `skipTests` system variable is defined in the shared configuration, and therefore does not need to be added to the pom files of the client library.
> build: remove custom skip tests variable

- .github/sync-repo-settings.yaml
Removes clirr and linkage-monitor as required CI steps from the LTS version, since they do not support old versions (not HEAD) of the library.
> chore: removes clirr/linkage-monitor from 3.3.3-sp

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractSqlScriptVerifier.java
Re-adds test utility method, which had its signature changed. Marks the re-added method as deprecated and delegates execution to the new one. This should prevent compilation errors for the projects that are using it.
This was preventing updates of the java-spanner-jdbc project to the latest BOM (see https://github.com/googleapis/java-spanner-jdbc/pull/464).
> fix: re-adds test utility method for connection

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractSqlScriptVerifier.java
Re-adds verifyStatementsInFile with old signature and marks it as deprecated.
> fix: re-adds test method verifyStatementsInFile

- samples/snippets/src/test/java/com/example/spanner/EncryptionKeyIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
The encrypted database/backup/restore tests sometimes fail because of other (parallel) backup operations. To reduce the probability of this, we will try to move these integration tests into the monolitic test run that tests all samples serially.
Updates #1019
> test: move encrypted tests to monolith tests

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
Adds a test to verify that the callback function of an `AsyncResultSet` is not called while the result set is paused.
> test: verify that callback is not called while paused

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextTest.java
Adds bufferAsync methods to TransactionContext. The existing buffer methods were already non-blocking, but the async versions also return an ApiFuture, which make them easier to use when chaining multiple async calls together.
Also changes some calls in the AsyncTransactionManagerTest to use lambdas instead of the test helper methods.
Fixes #1126
> feat: add bufferAsync methods

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
An AsyncResultSet that was PAUSED and then CANCELLED, would continue to invoke the callback until the callback would call tryNext(). If the callback never called tryNext(), the spinning would continue until the entire result set had been consumed.
Fixes #1191
> fix: stop invoking callback after pausing and cancelling result set

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Adds tests for checking that CREATE/ALTER/DROP VIEW statements are recognized
as valid DDL statements in the Connection API. This means that these statements
will be sent to the UpdateDatabaseDDL RPC by the Connection API. The Connection
API does not itself do anything with these statements, and any support for
these statements depends completely on whether the backend supports it.
> test: add tests for parsing VIEW DDL statements

- samples/snippets/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/5310
> docs: document retry settings in sample

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
The test backup operation could finish before the sample can cancel it. If that happened, the sample would not print any information and the corresponding test case would fail, although the sample does take this into consideration as a valid scenario.
Fixes #1211
> test: backup operation could finish before it is cancelled

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Increases the allowed wait time for the threads to shut down. Note that the full wait time will only be used if the threads do not shut down timely, which means that this does not slow down the test case under normal circumstances.
Fixes #1217
> test: increase wait for threads to shut down

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/CredentialsService.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
This enables a user to specify a base64 encoded JSON string that contains the credentials that should be used for the connection. This removes the requirement to write the JSON string to a file before it can be used for a connection.
This property is the same as the `spring.cloud.gcp.spanner.credentials.encoded-key` property that is supported by [spring-data-cloud-spanner](https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.M1/reference/html/_spring_data_cloud_spanner.html). 
Fixes https://github.com/googleapis/java-spanner-jdbc/issues/486
> feat: support encoded credentials in connection URL

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
The Spanner Async API uses an `ExecutorProvider` for producing rows for an `AsyncResultSet`. The default that is automatically created is fine for most use cases, but did not allow users to override the default settings that are:
- a pool containing at most 8 threads
- threads automatically time out after 1 minute if they are not used
This PR adds the possibility for users to supply their own `ExecutorProvider` to use with the async API.
Fixes #1262
> feat: support setting an async executor provider

- samples/snippets/src/main/java/com/example/spanner/CreateInstanceWithProcessingUnitsExample.java
Updates the LCI samples to be accordingly to the spec. Instead of printing out the processing units directly from the instance that is created, another getInstance is done in order to retrieve the information.
> samples: updates lci samples

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
Increase the wait time for a `DatabaseNotFound` error, as it can take a little while before Cloud Spanner actually sends that error for a `SELECT 1` query.
Also enable the `ResourceNotFound` tests on the emulator, as the emulator now includes `ResourceInfo` in the returned errors.
Fixes #1272
> test: increase timeout and enable tests on emulator

- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
Use a separate Cloud Spanner instance to execute the encrypted database and backup tests to prevent multiple parallel backup operations on the same instance from interfering with each other.
Fixes #1273
> test: use separate instance for encrypted backup test

- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
Shortens the display name of the test instance that is created for each sample test run.
(I've been able to verify that the test instance can now be created, but the test uses a fixed encryption key that is not available in my test project, so I've not been able to run the entire test. These tests are also only executed as part of the nightly build, so we'll only see the actual result tomorrow.)
Fixes #1277
> fix: shorten the test instance name

- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
> test: delete backups before instance

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
Adds test for numeric as primary key.
> test: adds test for numeric as primary key

- google-cloud-spanner-bom/pom.xml
All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.
> chore: remove distributionManagement section

- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
> test: retry backup deletion if optimization is still pending

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
The list of available statistics packages will change over time, meaning that the samples need to use 'latest' to prevent build failures when a package has been cleaned up by the backend.
See also https://github.com/googleapis/nodejs-spanner/pull/1436
Fixes #1273
> docs: use 'latest' stats package in samples to prevent build failures

- .github/sync-repo-settings.yaml
- .github/workflows/samples.yaml
- synth.py
Since the samples tests are not being run on every PR, we add a step to at least compile the samples to make sure we don't introduce any hard failures.
> chore: add ci task to compile samples

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
Some assertions had no effect, because the matcher was never called. In this PR we change the assertions to properly call the matchers.
The matchers that were not called were of the form:
```
assertThat("...".contains("expression"));
```
We moved them to be:
```
assertThat("...").contains("expression");
```
We decided not to migrate all the assertions from `assertThat` to the corresponding `assertEquals`, `assertTrue`, ... to minimise the changes in this PR. The migration should be done separately.
> tests: value test fix

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerThreadsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
The tests that check that a Spanner instance closes all threads that it is
using was counting the total number of threads with a fixed thread name. That
also meant that if any other test would fail to (timely) close its own threads,
the thread tests could fail as a result. This is now mitigated by using unique
names for the threads for the tests, so the test can check only for its own
threads instead of all Spanner threads. The additional option that is added to
SpannerOptions is package-private, which means that the tests also need to
move to the same package. The thread tests have therefore been moved to a
separate file in the normal Spanner package.
> test: use unique name for threads in test

- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
- samples/snippets/src/test/java/com/example/spanner/CreateDatabaseWithDefaultLeaderSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/GetDatabaseDdlSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/QueryInformationSchemaDatabaseOptionsSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SampleTestBase.java
- samples/snippets/src/test/java/com/example/spanner/UpdateDatabaseWithDefaultLeaderSampleIT.java
We have configured a multi-regional instance for CMMR sample tests, so we can unskip the tests now.
> test: unskip cmmr tests

- google-cloud-spanner/pom.xml
The current version (1.1.0) of grpc-gcp is available via java-shared-dependencies.
> chore: remove grpc-gcp version from pom.xml

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Use a dummy emulator-project when no default project is set for the environment
and the SPANNER_EMULATOR_HOST environment variable has been set.
Replaces #1345
> feat: use dummy emulator-project when no project is set

- .github/workflows/ci.yaml
This only works with the latest version of the dependencies, so it won't work with the LTS versions.
> chore: remove linkage monitor ci step

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ChecksumResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/KeyTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
- google-cloud-spanner/src/test/resources/com/google/cloud/spanner/read_tests.json
Allow users to read and write to Cloud Spanner databases using the JSON type through the client libraries.
Integration tests here: https://github.com/zoercai/java-spanner/pull/1
> feat: add support for JSON data type

- .github/sync-repo-settings.yaml
Removes linkage-monitor and dependency checks from LTS branch (6.4.4).
> chore: remove unused steps from sync repo settings

- samples/snippets/src/test/java/com/example/spanner/SampleTestBase.java
There was a bug on dropping databases / deleting backups after the sample tests where we were trying to delete in the regional instance first and if an exception was thrown, we would try to delete on the second instance. This did not work, because the delete / drop operations do not fail if the database / backup are not found in the instance, the call simply returns.
In this PR we have applied both deletes one after the other to fix the issue, instead of relying on the exceptions.
> fix: drop databases after sample tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementImpl.java
Do not serialize java.util.regex.Pattern and executor fields in client side statement. This caused an issue with Java 16 compilation, where an IllegalAccessException is thrown during JSON serialization of such fields.
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @5fcbae9d
at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:357)
at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:297)
at java.lang.reflect.Field.checkCanSetAccessible (Field.java:177)
at java.lang.reflect.Field.setAccessible (Field.java:171)
at …
```
> fix: do not serialize unnecessary fields

- google-cloud-spanner/pom.xml
Integration tests are timing out at the 54 minute mark. It correlates well with the current forkedProcess timeout set for failsafe plugin which is 3000 seconds (50 minutes).
Here we increase it to 6000 seconds to see if the issue is resolved.
> chore: increase integration tests timeout

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
> fix: sessions were not always removed from checkedOutSessions

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
> fix(3.1.x): sessions were not always removed from checkedOutSessions

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
> fix(4.0.x): sessions were not always removed from checkedOutSessions

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
> fix(5.2.x): sessions were not always removed from checkedOutSessions

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
> fix(3.3.3-sp): sessions were not always removed from checkedOutSessions

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
> fix(3.3.x): sessions were not always removed from checkedOutSessions

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
A transaction context should be marked as closed after it has been used, so it can throw a logical error if someone tries to reuse it for a second transaction.
> chore: mark transaction context as closed after use

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
If a StreamingReadRequest that included a BeginTransaction option was retried as a result
of a transient error (UNAVAILABLE), the fact that the BeginTransaction option was included
would not be registered for the retried request. This could cause a transaction to fail if
the retried request returned an Aborted error, and that Aborted error was caught by the
application.
> fix: keep track of any BeginTransaction option for a Read

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- Removes 3.3.3-sp as protected branch (current LTS version is 6.4.4-sp)
- Removes sample compile step from protected branches CI
> chore: update protected branches ci / releases

- samples/snippets/src/main/java/com/example/spanner/TagSample.java
- samples/snippets/src/test/java/com/example/spanner/SampleTestBase.java
- samples/snippets/src/test/java/com/example/spanner/TagSampleIT.java
Adds transaction / request tagging samples.
Supersedes https://github.com/googleapis/java-spanner/pull/1478.
> samples: add transaction / request tagging samples

- google-cloud-spanner/pom.xml
- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
Uses the same region as the CMEK keys for the test instances
> test: fixes cmek related tests

- .repo-metadata.json
- google-cloud-spanner-bom/pom.xml
The test jar was wrongly removed during the owlbot migration.
`google-cloud-spanner-bom` has been added to an exclude list for owlbot. This means owlbot will not add new dependencies to the bom when a new version is introduced. Renovate bot will still update the versions and no other owlbot feature changes.
> fix: re-adds test-jar to bom definition

- .github/release-please.yml
- .github/sync-repo-settings.yaml
- README.md
End of life support for 3.1.x branch as of 2021-12-17. This change removes the configuration for this branch.
> chore: eol support for 3.1.x

- .readme-partials.yaml
> feat: Updating readme with new gfe latency metrics

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchReadOnlyTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
-   remove session.close() from close() method implementation in
BatchReadOnlyTransactionImpl class.
-   add a cleanup() method to BatchReadOnlyTransaction interface
and give user the control to delete session when the session
is no longer in use.
-   add tests for txn.cleanup() method.
Fixes #1651 ☕️
> fix: do not delete session in close method for BatchReadOnlyTransactionImpl

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadOnlySpannerTest.java
DirectExecuteResultSet, which is used in the Connection API, directly
executes any query that it is given without the need to call
ResultSet.next() first. This also makes it possible to get the ResultSet
metadata from the result without the need to calling ResultSet.next()
first.
> fix: allow getting metadata without calling next()

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
Statement parsing is currently done internally in the Connection API do
determine what RPC to execute on the backend. The parsing is however
also very useful to some other applications, specifically PgAdapter,
which can use this to determine what response to send to a PG client.
This makes the parse method and related class and methods public, but
marks them as InternalApi, so they can be used in PgAdapter. This
follows the same pattern that was used to expose certain methods in the
Connection API for the JDBC driver.
> chore: make statement parsing public (marked as InternalApi)

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITResultSetGetValue.java
Allows for getting JSON values using resultSet.getValue(). This was not possible before, because a mapping was missing.
Overrides the getString method in json values to allow for getString and getStringArray on json values.
> feat: allows for getting json columns using getValue

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
Automatic dialect detection should not rely on `pg_catalog` being present in the `information_schema` to determine that it is a PostgreSQL database. Instead, the presence of an upper/lower case `INFORMATION_SCHEMA` / `information_schema` should be used to determine which of the two dialects is being used.
> fix: use information_schema instead of pg_catalog for dialect detection

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Support untyped null values in statement parameters for the mock Spanner
server used for testing.
> test: handle untyped null parameters in Mock Spanner server

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Added the string "pg-adapter" in the list of allowed client library token, so that when PG Adapter connects via client library by passing the string "pg-adapter" in the user-agent header, it doesn't get discarded. Also, added the one test case to cover the same.
Fixes [b/213946108](http://b/213946108)
> feat: Track PG Adapter usage from user-agent headers

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java
Following exception is thrown:
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION.
So, changing the catch in order to catch all appropriate exceptions.
Fixes #1652 ☕️
> fix: catch ExecutionException for op.getName

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
PostgreSQL supports newline characters in string literals and quoted
identifiers. Trying to execute a statement with a string literal or
quoted identifier that contained a newline character would cause an
'Unclosed string literal' error.
Fixes #1730
> fix: PostgreSQL supports newline in quoted literals and identifiers

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Adds a helper method to get the parameters from a PostgreSQL query. This
is needed for DESCRIBE statement messages in PGAdapter, as it must
return the data types of all query parameters in a query string. Even
though this parser is not able to determine the parameter types, it is
able to determine the number of parameters. This again makes it possible
to PGAdapter to return Oid.UNSPECIFIED for each parameter in the query
string, which is enough for most clients.
cc @pratickchokhani
> feat: parse query parameters in PostgreSQL query

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionTest.java
Any error that was returned by BatchCreateSessions should also be set as
the result of the auto-detect dialect query, as the query will never be
able to return a result for the dialect when session creation fails.
Fixes #1759
> fix: return errors from BatchCreateSession to dialect detection

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
Use an AtomicInteger for dbseq to ensure unique database names if
multiple tests try to create a database in parallel.
Updates https://github.com/googleapis/java-spanner-jdbc/issues/820
> test: use an AtomicInteger for dbseq

- README.md
- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlBatchTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlClientTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SingleUseTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITDdlTest.java
Adds support for the CREATE DATABASE statement in the Connection API.
The statement can only be used with a `SingleUseTransaction` (i.e. auto
commit mode). It is not supported in DDL batches. The database that is
created will have the same dialect as the current database that the user
is connected to.
Fixes #1844 
Towards b/229420558
> feat: support CREATE DATABASE in Connection API

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
This commit aims to resolve the RESOURCE_EXHAUSTED errors due to
number of databases in an instance reaching the maximum limit.
We delete all the databases of an instance, which are more than 24 hours old, before running the tests.
Fixes #1832  ☕️
> test: drop old databases from instance before running integration tests.

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
Adds support for PostgreSQL dialect to RandomResultsGenerator
> test: support PostgreSQL dialect for RandomResultsGenerator

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/CredentialsProviderTest.java
Adds support for setting a `CredentialsProvider` instead of a
credentialsUrl in a connection string. The `CredentialsProvider` reference
must be a class name to a public class with a public no-arg constructor.
This option is available in the Connection API, which means that any
client that uses that API can directly benefit from it (this effectively
means the JDBC driver).
The option will only be available in the JDBC driver once the dependency on the client library in the JDBC driver has been updated to a version of the Java client library that contains this change.
Fixes b/231174409
> feat: support CredentialsProvider in Connection API

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
A connection will automatically rollback any active transactions when
the connection is closed. If the rollback would throw an exception, the
close would fail and the connection would still be marked as open. This
fix adds a simple ignore error handler when rolling back a transaction
when the connection is closed.
> fix: ignore errors during Connection.close()

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Adds support for the ANALYZE statement. This statement is sent to the UpdateDatabaseDdl RPC.
Fixes b/232483941
> feat: support analyze DDL statement

- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .github/workflows/samples.yaml
- .kokoro/build.sh
- .kokoro/common.sh
- .kokoro/dependencies.sh
- owlbot.py
Testing with GraalVM SDK 22.1.0. (The target branch of this pull request is Mridula's test-compatibility branch).
> ci: ci to build with JDK 11 (cont.)

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
Gracefully catch and ignore `RejectedExecutionException`s that might happen while closing a connection. This prevents the `SpannerPool` from holding on to connections that failed to close because of such an error.
> fix: gracefully ignore RejectedExecutionException during Connection#close()

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
The PostgreSQL parser that removes comments and checks the type of
statement should not consider a backslash inside a quoted literal or
identifier as an escape character. Instead, only double occurrences of
the same quotes as the begin/end quote should be considered as an escape
inside a quoted literal or identifier.
Fixes #1920
> fix: PostgreSQL parser should not treat \ as an escape char

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Tests that block comments embedded in other block comments are parsed correctly by the PostgreSQL parser.
> test: test embedded comment in comment

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ChannelUsageTest.java
This is to fix an issue where the test would fail if the value of the key changes in gRPC. See https://github.com/googleapis/java-spanner/pull/1960 for details.
> fix: Use the key instead of the value to verify the number of channels created in ChannelUsageTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java
Removing redundant calls to set the expiration time of backup. Expiration Time is already set in line 283.
> refactor: Removing duplicate calls to set expiration time

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/RetriableUpdate.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbortedTest.java
Retries of read/write transactions in the Connection API did not respect the analyze mode of update statements. This would cause updates to be executed using AnalyzeMode.NORMAL during retries, regardless of what was used during the initial attempt.
Fixes #2009
> fix: retries of updates in the Connection API ignored analyze mode

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
Latest internal jdk 11 build throws NoSuchFieldException when we use reflection on a reflection class. Gracefully skipping the test execution in such cases.
> test: skip SpanTest when NoSuchFieldException

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ChannelUsageTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Enable compression of network traffic from client to server.
See the below screenshots from Wireshark for tests that show that the compression works both ways. Note: The rate of compression will depend on the type of data that is being sent. The below example for client->server communication is for sending 1,000 very similar mutations to Spanner. That compresses very well with gzip. More random data will compress less.
> feat: enable client to server compression

- pom.xml
Fixes #2141, where the build failed with the enforcer check:
```
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for io.grpc:grpc-api:1.36.3 paths to dependency are:
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7
+-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7
+-io.grpc:grpc-auth:1.36.3
+-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7
+-io.grpc:grpc-core:1.36.3
+-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7
+-io.grpc:grpc-protobuf:1.36.3
+-io.grpc:grpc-api:1.36.3
...
```
> chore: skip enforcer check on gRPC dependency (6.4.4-sp branch)

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/NoRowsResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DmlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadOnlyTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/UnitOfWork.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AnalyzeStatementsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSetTest.java
Add the method analyzeUpdateStatement that returns the undeclared
parameters in an update statement. This allows connection based APIs
to return more metadata for a statement than is currently possible:
1. JDBC should return the parameter data types when PreparedStatement#getMetaData()
is called.
2. PGAdapter should return the parameter types when a DescribeStatement
message is received.
> feat: analyze update returns param types

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Partition.java
Make getters in Partition class public so that they can be accessed outside com.google.cloud.spanner package.
> chore: make Partition class getters public

- .kokoro/build.bat
> chore: ensure that java8 is used to run tests in kokoro windows job

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITProtoColumnTest.java
This PR includes Integration tests for following scenarios: 
-  Write & Read Proto Messages & Enums and array of it. 
- Check compatibility between ProtoMessage/Bytes & ProtoEnun/Int64. 
- Negative Case when incorrect Proto object is provided while reading the data.
-   Parameterised queries, Primary Keys and Indexes.
> test: Proto Column Integration tests

- jitpack.yml
Adding Jitpack Configuration file, it's required for Verily to start prototyping on Java Client
> Configured jitpack.yml to use OpenJDK 11

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IsRetryableInternalErrorTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
The Spanner server can return an internal error closing the connection stream. When this happens an InternalException is thrown with a specific EOS message.
This case need to be retried for all the operations.
> fix: retry on RST_STREAM internal error

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
* Issue - https://github.com/googleapis/java-spanner/issues/2206
* Root Cause - In cases where we are receiving `AbortedException`, the retry delay is set as `-1` for the exception. Negative value is not an acceptable input to `Thread.sleep()` method and hence we are getting `IllegalArgumentException`. This is resulting in flaky unit test behaviour.
> fix: prevent illegal negative timeout values into thread sleep() method while retrying exceptions in unit tests.

- .kokoro/build.bat
- README.md
The Windows build was failing due to incorrect JAVA11_HOME env.
```
Temurin11 has been installed.
temurin11 may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of temurin11 was successful.
Software installed to 'C:\Program Files\Eclipse Adoptium\jdk-11.0.18.10-hotspot\'
openjdk11 v11.0.16.20220913 [Approved]
openjdk11 package files install completed. Performing other installation steps.
The install of openjdk11 was successful.
Software install location not explicitly set, could be in package or
default install location if installer.
Chocolatey installed 2/2 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
T:\src>set …
```
> chore: fix kokoro windows java 8 ci by setting correct JAVA11_HOME

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerStatementParser.java
these are defined in the base class AbstractStatementParser:
https://github.com/googleapis/java-spanner/blob/30a32e9f8c133fc0efa24f33807905407f1dd208/google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java#L475-L486
> refactor: remove local variables, use static constants

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
The recent change that made decoding BYTES and ARRAY<BYTES> lazy did not update all code paths in the mock Spanner server that is used for testing. This meant that tests that tried to use ARRAY<BYTES> query parameters would run into a ClassCastException. This problem only occurs in (internal) test code and does not affect user code.
> test: fix mock server ARRAY<BYTES> parameter cast

- README.md
- google-cloud-spanner/pom.xml
Reverts googleapis/java-spanner#2363
@rajatbhatta It seems that we need to revert this, as the integration tests have started failing after this update with an error related to this version bump.
> Revert "build(deps): update dependency org.jacoco:jacoco-maven-plugin to v0.8.9"

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Fix a potential NullPointerException in the mock server when a statement uses a parameter of type ARRAY<BYTES> with a null element in the array.
> test: fix NullPointerException in mock server

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Add tests to verify that untyped null statement parameters work with both GoogleSQL, PostgreSQL and the emulator.
Verifies that https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/31 has been fixed.
> test: untyped nulls as statement parameters

- google-cloud-spanner-executor/pom.xml
- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
Remove an additional dependency on org.jetbrains.annotations and use javax.annotation.Nonnull.
> fix: use javax.annotation.Nonnull in executor framework

- .github/sync-repo-settings.yaml
- .github/workflows/ci.yaml
- .github/workflows/integration-tests-against-emulator.yaml
- .kokoro/build.sh
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
I found we can simplify the Java 8 test via surefire's jvm property (document: https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#jvm)
Changing the required checks to use "dependencies (17)" only. There's no point running the dependencies checks for different JDK versions.
Once approved, I will change the required checks in repository settings to merge this pull request.
> test: simplifying Java 8 test via jvm property

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
Make retries of administrative requests that fail because the administrative request limit has been exceeded optional. This allows users to apply custom retries or other custom handling for these errors.
Addresses #2454
> feat: make administrative request retries optional

- google-cloud-spanner-executor/pom.xml
- google-cloud-spanner/pom.xml
- pom.xml
Temp exclusions are needed to avoid dependency version discrepancy due to 3.23.2. 
For more context: https://github.com/googleapis/sdk-platform-java/pull/1791#issuecomment-1601587713
@suztomo  Can you take a look if this temp fix looks okay?
Closes #2509
> deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v3.12.0.with temp exclusions.

- samples/snippets/src/test/java/com/example/spanner/UpdateDatabaseSampleIT.java
Local compilation is failing due to missing imports. The change adds the missing imports for integration test file. We would separately be investigating why these compilation issues were not detected earlier.
> fix: add imports used in sample files.

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
BEGIN_COMMIT_OVERRIDE
feat: Enable leader aware routing by default. This update contains performance optimisations that will reduce the latency of read/write transactions that originate from a region other than the default leader region.
END_COMMIT_OVERRIDE
> feat: Enable leader aware routing by default

- .github/sync-repo-settings.yaml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractLazyInitializer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncRunner.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceConfigInfo.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Operation.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Session.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TimestampBound.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManager.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunner.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractSqlScriptVerifier.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SqlScriptVerifier.java
Java SDK team is installing a job to compile doc errors as part of - https://github.com/googleapis/java-spanner/pull/2515 . The job won't succeed with existing errors. This PR fixes the existing errors in docs.
Command for testing - `mvn javadoc:javadoc javadoc:test-javadoc -B -ntp`
> docs: fixing errors 

- README.md
- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
Use the streamWaitTimeout that has been set on the call context when polling from the gRPC stream. This prevents the stream from blocking forever if for some reason the stream is no longer delivering data, and also no error is propagated to the client.
The default stream wait timeout that is set for all call contexts is 30 mins. This value can be overridden by configuring a custom call context for a specific query.
Fixes #2494
> fix: apply stream wait timeout

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatement.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementExplainExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementNoParamExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementPgBeginExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementSetExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/BeginPgTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionStatementWithNoParametersTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionStatementWithOneParameterTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SetPgSessionCharacteristicsTest.java
Refactor the internal interface of client-side statements so these receive the entire parsed statement, including any query parameters in the statement. This allows us to create client-side statements that actually use the query parameters that have been specified by the user.
This refactor was pulled out of #2540 to make that PR smaller.
> chore: refactor client side statements to accept the entire parsed statement

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/LongRunningSessionsBenchmark.java
Adding benchmarks for long running sessions cleanup feature introduced as part of - https://github.com/googleapis/java-spanner/pull/2419 .
> test: add benchmark for long-running sessions clean up task.

- .github/sync-repo-settings.yaml
- .kokoro/build.sh
- README.md
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnvTest.java
Remove native image tests from the list of required checks, as they fail continuously.
> build: remove native image tests from required checks

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/MergedResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/MergedResultSetTest.java
Calling getColumnCount() would fail for __empty__ ResultSets that were returned for partitioned queries. The reason for this was that the number of columns would be calculated based on the last seen row. This would not work for ResultSets without any rows at all.
> fix: getColumnCount would fail for empty partititioned result sets

- README.md
- samples/snippets/pom.xml
- samples/snippets/src/main/java/com/example/spanner/TransactionTimeoutExample.java
- samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Our current samples show how to set timeout and retry settings for all RPC invocations for a given RPC method, and how to set a timeout for a single statement, but we did not have a sample for setting a timeout for an entire transaction. This is something that customers have been asking multiple times. This sample shows how a transaction timeout can be set by using a gRPC context with a timeout.
> docs: add sample for transaction timeouts

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Allow comments in PostgreSQL query strings for extracting parameter definitions. The comments need to be preserved, as they could contain query hints.
> chore: allow comments in PG strings

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/EmulatorUtil.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/EmulatorUtilTest.java
The autoConfigEmulator=true flag in the Connection API can be used to automatically connect to the emulator and automatically create the instance and database that is being referenced. This makes running a quick test on the emulator much easier, as all you need to do is to configure the correct (JDBC) connection URL, and it will automatically work. This mode would always create a GoogleSQL database. This change adds support for creating a PostgreSQL database if the user specifically sets the dialect in the connection string.
> feat: support PostgreSQL for autoConfigEmulator

- .kokoro/build.bat
- README.md
Windows build fails due to incorrect JAVA11_HOME env. This PR corrects it to latest version to fix the failing window builds.
> fix: fix kokoro windows java8 ci

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
Adds a test for blind writes before executing a read or SQL statement in a read/write transaction.
> test: add a test for blind writes

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
De-duplicate code that is equal for both the sync and async version of the executeBatchUpdate methods.
> chore: deduplicate code for batch updates

- README.md
- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ExceptionMockServerTest.java
Adds an execute method to the Connection API that allows the caller to specify the allowed result types. This can be used by driver implementations, such as JDBC, to use a single execute method in the Connection API, while still making sure that the method only executes statements that it should.
The current executeUpdate method in the Connection API does not overlap completely with semantics of executeUpdate in JDBC, as JDBC allows any statement type that does not return a ResultSet to be executed with that method. The Connection API only allows statements that return an update count.
Instead of modifying the executeUpdate method in the Connection API to match the semantics of JDBC (which would be a breaking change), this method can be used generically for all execute*** methods in the …
> chore: add execute method with allowed return types

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/CredentialsProviderTest.java
Disable Connection URL properties that dynamically invoke code by default. These properties can now only be used if the corresponding System property has been enabled. This gives users control over whether they want to enable these properties in their applications or not.
You should only enable the use of these properties as long as untrusted end users cannot dynamically set these. That is; If your application is a public service that allows end users to set a Connection URL, then you should not enable the use of these properties, as it would allow a user to try to specify a credentials or channel provider class that is not a valid provider. The constructor of the selected class would in that case still be invoked.
> feat: disable dynamic code loading properties by default

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbortedTest.java
The mock server that is used for testing contained a queryAndThen(..) method that did not do anything with the 'and then' part. This PR fixes that, and adds an additional test using that method. That test shows what happens with a bit-reversed sequence when a transaction is aborted.
> test: fix the queryAndThen method in the mock test server

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SamplesMockServerTest.java
- samples/snippets/src/main/java/com/example/spanner/CustomTimeoutAndRetrySettingsExample.java
The timeout and retry sample used 60 seconds for both initial, max, and total timeout. It also used a 1.0 multiplier for the timeout value. This made it impossible to explain how to set an increasing RPC timeout value. It also rendered adding the DEADLINE_EXCEEDED error code as a retryable code superfluous.
> docs: improve timeout and retry sample

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsSlowTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Requests are made to wait till a session is available. We are introducing a session pool option `acquireSessionTimeout` and a public method `setAcquireSessionTimeout` in the `SessionPoolOptions` class that will allow to specify a timeout value for requests. Post this timeout application will receive a `RESOURCE_EXHAUSTED` error. If this option is not passed, the client library will wait for 60s by default.
* Sample Usage
```
SessionPoolOptions sessionPoolOptions =
SessionPoolOptions.newBuilder().setAcquireSessionTimeout(Duration.ofMillis(60)).build();
SpannerOptions.Builder builder =
SpannerOptions.newBuilder()
.setProjectId("my-project")
.setChannelProvider(channelProvider)
.setCredentials(NoCredentials.getInstance())
.setSessionPoolOption(sessionPoolOptions);
```
> feat: add session pool option for modelling a timeout around session acquisition.

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Adds support for using a System property to set the default session pool ordering. The default ordering is LIFO. This can be changed to FIFO and RANDOM for users who need/want that.
> chore: add a system property to set session pool ordering

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Rename the System property that is used to set the number of core threads for the Async API to a namespaced name to be consistent with other System properties. The name name is
`com.google.cloud.spanner.async_num_core_threads`.
> chore: rename system property for core threads for Async API

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDmlReturningTest.java
While debugging flaky issue - https://github.com/googleapis/java-spanner/issues/2629 , it was noticed that `ITDmlReturningTest` is not using the right convention for `assertEquals` method. This PR swaps the value so that debugging readability is improved.
For ex - The following error message in the above issue is confusing due to this swap between expected/actual values.
```
java.lang.AssertionError: expected:<1> but was:<2>
```
> test: swap expected and actual values in DML returning tests.

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionImplTest.java
Noop in case there is no change in  autocommit value for setAutocommit() method
> fix: Noop in case there is no change in  autocommit value for setAutocommit() method

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Removes the double inclusion of the standard client lib token when no custom client lib token has been set. Also reuses more of the standard feature for setting the client lib token, instaed of appending the standard token at the moment that we are creating the gRPC stub. This should reduce the probability that anyone who might be using a custom header or custom client in some way will get it wrong.
> chore: remove double client lib token header

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Instance.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceInfo.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceInfoTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
- Add the ability to create / update an instance with autoscaling config
- Note that now user can only specify one of the node_count, processing_units or autoscaling_config as the compute capacity for an instance.
- Add the ability to see autoscaling config with an instance
> feat: Add support for Managed Autoscaler

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
The Connection API would always use the default emulator host when autoConfigEmulator=true was set in the connection string. This makes it harder to override the host name for the emulator when you also want the emulator to automatically create the instance and database that you connect to, as the only way to set it is to add it to the connection string.
> fix: respect SPANNER_EMULATOR_HOST env var when autoConfigEmulator=true

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Dialect.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
JDBC must be able to return the type name of a query parameter. Currently, that is done with a custom implementation in the JDBC driver. This adds a method to the Spanner client for the same, so the feature is in a more logical place.
> chore: add method for getting the backend type name

- google-cloud-spanner-executor/README.md
The google-cloud-spanner-executor module is not for Spanner library users. Adding a note to avoid confusion for those who browse this repository.
> chore: README for google-cloud-spanner-executor module

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ChannelUsageTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/FakeClock.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolMaintainerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementTimeoutTest.java
Several tests spammed the build log with various warnings and other log items that were irrelevant for the test output. This change removes as much as possible of that.
> test: reduce test log spam

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Adds tests to verify that concatenated literals work with the statement parser.
> test: add tests for concatenated literals

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/MergedResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/PartitionedQueryMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITProtoColumnTest.java
This PR has the following changes in test files
1. Use `try-with-resource` block in Proto Columns integration tests to free up resources and sessions.
2. Add `PROTO` and `ENUM` types to `testGetAllTypesAsString` unit test.
> test: update proto columns test

- google-cloud-spanner-bom/pom.xml
google-cloud-spanner-executor is for Google-internal use. No customers should use it. It has been added to the BOM accidentally. (b/320677880)
> fix: remove google-cloud-spanner-executor from the BOM

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Add a cache for the statement parser that is used in the Connection API. This will reduce the number of times that a SQL string needs to be parsed by the JDBC driver and PGAdapter.
> chore: use a cache for the statement parser

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
The cleanup function used to remove old test databases did not remove the drop protection flag before trying to drop a database.
> chore: remove drop protection before cleanup

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ThreadFactoryUtil.java
The virtual threads util that tries to create a virtual thread factory on JVMs that support this would fail on Java 20, because:
1. Java 20 supports virtual threads as an experimental feature. This means that the code is present.
2. The feature is by default disabled, and throws an UnsupportedOperationException.
This fix takes the above into account and returns null if a user tries to create a virtual threads factory on Java 20 with experimental features disabled.
> fix: ignore UnsupportedOperationException for virtual threads

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/QueryOptionsTest.java
Statements that were executed using the Connection API and that were not found in the statement cache (that is; it was the first time it was executed), would not use the default query options that had been set for the connection. This would mean that for example an optimizer version that had been set for the connection would not be used the first time a given query string would be executed using a connection. All subsequent executions of the statement would use specified optimizer version.
This change ensures that both the first and all following executions of the statement use the default query options that have been set.
> fix: use default query options with statement cache

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
This PR fixes the following issues,
1. When export was done on `PROTO` type it was throwing a cast exception as follows,
```
Caused by: java.lang.ClassCastException: class com.google.cloud.spanner.AbstractResultSet$LazyByteArray cannot be cast to class com.google.cloud.ByteArray (com.google.cloud.spanner.AbstractResultSet$LazyByteArray and com.google.cloud.ByteArray are in unnamed module of loader 'app')
```
2. Add `ENUM` compatibility for `getLongArray` method.
3. `null` check for `PROTO` and `ENUM`
> fix: cast for Proto type

- .github/workflows/unmanaged_dependency_check.yaml
- README.md
@arpan14 This is is the implementation for the one I got your review in go/cloud-sdk-java-dependency-governance-design. This check will avoid accidentally adding a third-party dependency.
b/320677880
> ci: unmanaged dependency check

- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
- google-cloud-spanner-bom/pom.xml
- owlbot.py
- pom.xml
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central in https://github.com/googleapis/java-spanner/pull/2852/f
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
> chore: use sdk-platform-java-config to consolidate build configs

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStruct.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITProtoColumnTest.java
**Issue**: When running `ITProtocolumnTest` locally
```
java.lang.ClassCastException: class com.google.protobuf.Value cannot be cast to class com.google.cloud.spanner.AbstractResultSet$LazyByteArray (com.google.protobuf.Value and com.google.cloud.spanner.AbstractResultSet$LazyByteArray are in unnamed module of loader 'app')
at com.google.cloud.spanner.GrpcStruct.getProtoMessageInternal(GrpcStruct.java:385)
at com.google.cloud.spanner.AbstractResultSet.getProtoMessageInternal(AbstractResultSet.java:326)
at com.google.cloud.spanner.AbstractStructReader.getProtoMessage(AbstractStructReader.java:301)
at com.google.cloud.spanner.ForwardingStructReader.getProtoMessage(ForwardingStructReader.java:423)
at com.google.cloud.spanner.it.ITProtoColumnTest.testProtoColumnsUpdateAndRead(ITProtoColumnTest …
```
> fix: add ensureDecoded to proto type

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStruct.java
#2846 has refactored the result set class. However the `writeReplace` method was not updated. This PR fixes it.
**Impact**: This will break the import export functionality in Pantheon and dataflow templates.
The error is as follows
```
Caused by: java.lang.IllegalArgumentException: Unable to encode element '[string_value: "Singers5"
, string_value: "1"
, string_value: "CgFB"
, null_value: NULL_VALUE
]' with coder 'SerializableCoder(com.google.cloud.spanner.Struct)'.
org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:300)
org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
org.apache.beam.fn.harness.data.PCollectionConsumerRegistry$SampleByteSizeDistribution.tryUpdate(PCollectionConsumerRegistry.java:509) …
```
> fix: fix write replace in grpcStruct

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Adds support for OpenTelemetry metrics in the Connection API.
> chore: add support for OpenTelemetry metrics to Connection API

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RandomResultSetGenerator.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/MergedResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/PartitionedQueryMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
The FLOAT32 type was only added to the com.google.cloud.spanner.RandomResultSetGenerator, but that generator misses multiple other types. The one in the .connection package should be used instead. This PR therefore deprecates the one that should not be used, and updates all tests that used the old one.
It also adds FLOAT32 to the .connection.RandomResultSetGenerator, which is used by a larger number of tests. This discovered a bug in the FLOAT32 NaN comparison, which is also fixed in this PR.
Note: The commit is not marked with 'fix:', as the feature has not yet been released.
> chore: fix float32 NaN comparison + deprecate generator

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AllTypesMockServerTest.java
Adds support for `float32` to the mock server for testing. Also adds a couple of tests that can be used to verify that the mock server supports all types, and that verifies that the client library reads and encodes all types correctly. These tests can be overridden by frameworks using the Java client (e.g. JDBC and PGAdapter) to verify that these also handle these types correctly when used through the API of that tool (I.e. through JDBC or PostgreSQL wire-protocol).
> test: support float32 in mock server

- samples/snippets/src/main/java/com/example/spanner/StatementTimeoutExample.java
Add a tag to the StatementTimeoutExample, so we can include this sample in the documentation.
> docs(samples): add tag to statement timeout sample

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
To enable Direct Access, [both `setAttemptDirectPath` and `setAttemptDirectPathXds` should be called](https://github.com/googleapis/sdk-platform-java/blob/4b44a7851dc1d4fd2ac21a54df6c24db5625223c/gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java#L373-L386) for gax to append the correct google-c2p scheme.
This PR adds a env var `GOOGLE_SPANNER_ENABLE_DIRECT_ACCESS` to control the enable/disable of Direct Access. When it is true, it calls `setAttemptDirectPathXds` which effectively turns on Direct Access (as `options.isAttemptDirectPath` is by default true and we don't need to call `setAttemptDirectPath` again).
> feat: allow attempt direct path xds via env var

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerStatementParserTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Generalize the various skip methods so these can be used for both dialects. Each dialect implements a number of abstract methods to indicate what type of statements and constructs they support. These methods are used by the generalized skip methods to determine the start and end of literals, identifiers, and comments.
This is step 2 of the refactor that is needed to share more of the code between the SpannerStatementParser and PostgreSQLStatementParser.
> refactor: generalize skip methods

- .kokoro/nightly/integration.cfg
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
- owlbot.py
Fixes test [failures]( https://fusion2.corp.google.com/ci;prev=s/kokoro/prod:cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-spanner%2Fpresubmit%2Fintegration-directpath-enabled/activity;view=grid/17486d25-7f06-431c-a6ae-8a6538e10fe8/invocations/17486d25-7f06-431c-a6ae-8a6538e10fe8/targets/github%2Fjava-spanner%2Fgoogle-cloud-spanner%2Ftarget%2Ffailsafe-reports%2Fintegration-directpath-enabled%2Fcom.google.cloud.spanner.it.ITDatabaseAdminTest/tests?q=java-spanner%2Fpresubmit%2Fintegration-directpath-enabled&s=p)
> test: fix ITDatabaseAdminTest failures

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
* Unit tests haven't been added in current PR. Will include in next PR which will contain the pool create/get methods for multiplexed session.
> chore: add multiplexed session implementations for CachedSession/SessionFuture  interfaces.

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
Adds an 'endpoint' connection URL property for the Connection API. This property can be used instead of adding the endpoint to the host group part of the Connection URL, which again removes the need to actually change the connection URL when connecting to for example the emulator from the JDBC driver. The latter can instead just add the endpoint to the Properties set that is given to the JDBC driver.
> feat: add endpoint connection URL property

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractLatencyBenchmark.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DefaultBenchmark.java
* using env variable to parameterize inputs via commandline.
* disabling warmup iterations
* reporting latency in ms
> chore: minor improvements to default benchmarks.

- README.md
- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
- google-cloud-spanner-executor/src/main/java/com/google/cloud/spanner/SessionPoolOptionsHelper.java
* By default this change will have no impact since no one is passing `SessionPoolOptions` in proto input. There will be a follow up PR to support this in systest.
* setUseMultiplexedSession is presently a package private method in `SessionPoolOptions` class. So in order to support it in sys-test we create a new helper class `SessionPoolOptionsHelper` which is in same package `com.google.cloud.spanner` and hence can set the method.
> chore: support multiplexed sessions in cloud client executor.

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PartitionId.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/PartitionIdTest.java
Verify that the given base64 string actually contains a PartitionId before deserializing the object. This prevents attempts to abuse this method to execute the constructor of other objects on the class path.
> chore: verify that stream contains PartitionId before deserializing

- .kokoro/build.sh
- .kokoro/presubmit/integration-multiplexed-sessions-enabled.cfg
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
* Using a different instance ID - `projects/gcloud-devel/instances/java-client-integration-tests-multiplexed-sessions` for this runner so that it does not compete for resources with other active tests.
* This runner is expected to fail since multiplexed sessions is not enabled in production. It will pass for PRs where we point to cloud-devel (just for test purposes).
> chore: add a new integration test runner for multiplexed sessions.

- .github/workflows/ci.yaml
- Creating a new target through which we can obtain unit test coverage using multiplexed sessions. The target uses an additional env variable `GOOGLE_CLOUD_SPANNER_ENABLE_MULTIPLEXED_SESSIONS: true` using which multiplexed sessions will get enabled in the tests.
- Any errors will be fixed as a follow up before multiplexed sessions is enabled. Currently it is not enabled.
> chore: add a CI target to run unit tests using multiplexed sessions

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanExceptionTest.java
In case of a storm of requests for sessions leads to the session pool being temporarily exhausted, the session pool will return RESOURCE_EXHAUSTED errors for those requests. That error was however not propagated to any additional threads that were also waiting for the same transaction, and would cause these threads to continue with the transaction even though no valid session had been assigned. This fix ensures that the exception is also propagated to any thread waiting for the session.
> fix: NullPointerException on AbstractReadContext.span

- README.md
- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
The underlying Spanner instance is often needed by the libraries that use the Connection API, and should therefore be made public.
> chore: make getSpanner a public method

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsSlowTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ChannelUsageTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionMaintainerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetrySpanTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadAsyncTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/PartitionedQueryMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
Tests have been parameterized or skipped when test runners pass the env variable `GOOGLE_CLOUD_SPANNER_ENABLE_MULTIPLEXED_SESSIONS`. We presently have created separate test runners (unit, emulator and integration tests) which run during pre-submits and test the multiplexed session code path.
**Pending Stuff**
1. `ChannelUsageTest` has been disabled (with a followup TODO) when multiplexed sessions is enabled. We are coordinating with GRPC team to see how this can be enabled. This is the only test which currently exudes a flaky behavior very frequently.
> chore: fix all unit tests  with multiplexed sessions.

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Clock.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/FailOnOverkillTraceComponentImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionMaintainerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTests.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolMaintainerMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolMaintainerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
* Changes the session pool maintainer clock to a singleton.
* Adds more tests for session pool maintenance.
* Makes sure the clock that is set in the options is used for all transactions.
> chore: use a singleton session pool clock

- .github/workflows/ci.yaml
> test: add job for running multiplexed session test using Java 8 runtime

- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITFloat32Test.java
1. Add support for FLOAT32 in cloud client executor
2. Also allow integration tests to run FLOAT32 type against prod
> chore: Support FLOAT32 in Cloud Client Executor

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementExecutor.java
Use a TaskWrapping executor in the Connection API to propagate the current OpenTelemetry context to the executor thread. This ensures that the context that is used in the end-user application is propagated to the Spanner client library, and tracing shows a full view of the spans from the application to the gRPC layer.
> chore: propagate otel context in Connection API

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientTest.java
Adds an environment variable that can be used to force-disable the use of multiplexed sessions.
> chore: add flag to force-disable multiplexed sessions

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetrySpanTest.java
> chore: wait for all spans to finish to fix flakiness in test

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/JavaVersionUtil.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientTest.java
Uses the gson Java version checker, which is more production-hardened than the custom one in the Spanner client. It seems that the Spanner implementation does not get it right on all versions on Windows.
> chore: use gson Java version util

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DelayedReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AllTypesMockServerTest.java
The metrics for multiplexed sessions were not included in the refactoring that moved multiplexed sessions out of the session pool. This change re-adds those metrics based on the new client for multiplexed sessions.
> fix: multiplexed session metrics were not included in refactor move

- .github/sync-repo-settings.yaml
> chore: mark multiplexed session integration test as required

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
The CreateSession calls are irrelevant to the test, as multiplexed sessions are not used for read/write transactions.
Fixes #3090
> chore: ignore irrelevant CreateSession calls in test

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Include the stack trace of where a session was checked out when the session pool is exhausted. This makes it easier to find the place in application code that is responsible for having checked out sessions, and potentially having leaked these.
> feat: include stack trace of checked out sessions in exception

- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
The sample tests that are running as nightly build are failing from 6 months with the following error:
```
ERROR] com.example.spanner.UpdateDatabaseSampleIT.testUpdateDatabase -- Time elapsed: 0 s <<< ERROR!
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: 
Instance not found: projects/gcloud-devel/instances/java-client-integration-test
``` 
The instance id `java-client-integration-test` does not exist in this project. Instead the instance that is there is `java-client-integration-tests`
https://screenshot.googleplex.com/4YnhRoyTcqAoAr7
> chore(spanner): update sample tests instance id

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/LatencyTest.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDmlTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResumableStreamIterator.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerMetadataProvider.java
Optimizes the standard query path slightly by adding some caching and removing regex matching that happened on the critical path of each query that was executed.
> perf: minor optimizations to the standard query path

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractBaseUnitOfWork.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractMultiUseTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DmlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/UnitOfWork.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AnalyzeStatementsTest.java
Executing analyzeUpdate in a DML Batch inside a transaction should be possible, as the parent transaction can be used for that.
> feat: allow DML batches in transactions to execute analyzeUpdate

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/MergedResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/PartitionedQueryMockServerTest.java
Calling getMetadata() on a MergedResultSet should be allowed without first calling next() in order to be consistent with other ResultSets that are returned by the Connection API.
> fix: allow getMetadata() calls before calling next()

- README.md
- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
The `SessionPoolOptions#setUseMultiplexedSessions(boolean)` method was made public by accident. This method is not intended for public use.
> fix: make SessionPoolOptions#setUseMultiplexedSession(boolean) package private

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Adds a small wait to the test to ensure no flakiness, as it could be that sessions are re-used instead of just waiting for new sessions to be created. The test however always creates 4 sessions.
Fixes #3106
> chore: add wait to test to prevent flakiness

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DelayedReadContext.java
Propagate the underlying cause of the ExecutionException as a RuntimeException directly, if this is already a RuntimeException. This keeps the behavior of multiplexed sessions and regular sessions equal, regardless whether the Delayed... route is taken for multiplexed sessions, or the direct route is used.
Fixes #3132
> chore: propagate RuntimeException from DelayedReadContext

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/OpenTelemetryTracingTest.java
Adds a 'transaction.retried' attribute to Connection API read/write transaction spans if it was retried. This makes it easier to search for transactions that were retried.
> chore: add transaction.retried attribute to traces

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractBaseUnitOfWork.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/UnitOfWork.java
The DmlBatch span that was created for DML batches was never used, as all traces were registered on the underlying transaction of the batch. The DmlBatch span was therefore always just an empty sibling span of the Transaction span, which did contain the traces of the statements that were executed.
> fix: remove unused DmlBatch span

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/OpenTelemetryTracingTest.java
When a transaction is rolled back to a savepoint instead of rolled back entirely, the transaction span should not be ended, as the transaction continues to live.
> fix: do not end transaction span when rolling back to savepoint

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Add a connection URL property for enabling API tracing, so it can be set in the JDBC connection URL.
> chore: add connection property for API tracing

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
There are a couple of unit tests that verify the behavior of non-retryable error code. This PR updates the error code since the existing `RESOURCE_EXHAUSTED` error code is made as retryable error code in https://github.com/googleapis/java-spanner/pull/3064
> test(spanner): update non-retryable error code in unit tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
Calling toBuilder() on a SessionPoolOptions.Builder with useMultiplexedSessions=true returned a Builder instance with useMultiplexedSessions=false.
> fix: SessionPoolOptions.Builder#toBuilder() skipped useMultiplexedSessions

- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
In some scenarios during systest execution the error description is getting masked and is shown as `null`. This makes debugging the error harder. Adding an additional log to print the exception along with stack trace.
b/350177934
Example:
The below logging happens at this place https://github.com/googleapis/java-spanner/blob/main/google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java#L2669-L2673.
```
2024-06-29 06:10:52.179275-07007   Jun 29, 2024 6:10:52 AM com.google.cloud.executor.spanner.CloudClientExecutor executeQuery
2024-06-29 06:10:52.179291-07007   INFO: Executing query Writes2-auto-1719665201034008-429/4011
2024-06-29 06:10:52.179298-07007   sql: "@{ spanner.require_enhance_query = true }\nSELECT\n  orderbyscan_67.a_4 AS col59,\n …
```
> chore(executor): print exception stacktrace in executor

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
Adds support for setting Read OrderBy.
Customers can set this option only for the Read API. This option will allow users to specify whether they want the results to be returned in primary key order (PRIMARY_KEY) or in an out of order (NO_ORDER). The NO_ORDER is significantly faster than KEY_ORDER, because spanner uses higher parallelism for non-ordered reads.
Go counterpart: https://github.com/googleapis/google-cloud-go/pull/10289
> feat: support Read RPC OrderBy

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
The future that is returned by commitAsync() seems to never finish in some cases. It is unknown exactly what causes it, and this change adds a number of safety precautions that should ensure that the future always returns a result eventually. This is always easier to debug and handle than a future that never returns a value.
> fix: make sure commitAsync always finishes

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
The test used the error code RESOURCE_EXHAUSTED to indicate that the server could not create any more sessions. This error code is now retryable, causing the test to become flaky. Change the error code to one that is not retryable.
Fixes #3224
> test: do not use RESOURCE_EXHAUSTED as it is retryable

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Earlier, gRPC-GCP maintains affinity using the [ApiConfig](https://github.com/googleapis/java-spanner/blob/main/google-cloud-spanner/src/main/resources/com/google/cloud/spanner/spi/v1/grpc-gcp-apiconfig.json) by looking into the gRPC messages to get an affinity key.
This PR sets the affinity manually to gRPC-GCP via call options. Reason - With multiplexed sessions we need to maintain transaction to channel affinity, and with regular sessions we need to maintain session to channel affinity.
Setting manual affinity will override the API config setting.
References:
1. Java client design and benchmarking - https://docs.google.com/document/d/1iQwAGCwvatdoGxvfucd0eFAysx6roGMxJsoyygX79NY/edit?resourcekey=0-feEwEwbAPxsA-QydfaG53A&tab=t.0
2. gRPC-GCP manual affinity design - …
> feat(spanner): set manual affinity incase of gRPC-GCP extenstion

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SavepointMockServerTest.java
> chore: unflake SavepointMockServerTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
- samples/native-image/src/main/java/com/example/spanner/InstanceOperations.java
- samples/snippets/src/main/java/com/example/spanner/CreateInstanceExample.java
- samples/snippets/src/main/java/com/example/spanner/CreateInstanceWithAutoscalingConfigExample.java
- samples/snippets/src/main/java/com/example/spanner/CreateInstanceWithProcessingUnitsExample.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/CreateInstanceExample.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/CreateInstanceWithAutoscalingConfigExample.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/CreateInstanceWithProcessingUnitsExample.java
As a part of an effort to lower `us-central-1` scaling risk we are moving instances (used for testing) that are created in `regional-us-central1` to `regional-us-east4`.
b/355497681
> chore(spanner): Update instance region

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITDmlReturningTest.java
The initialization code for ITDmlReturningTest was borked and initialized the database over and over again for each test method. This pushes Spanner into throttling the DDL requests, which again makes both this and other integration tests slow.
This reduces the execution time for ITDmlReturningTest from 864.9s to 70.84s.
Updates #3247
> test: speed up ITDmlReturningTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GfeLatencyTest.java
Improves the unit test execution speed from around 2m15s to around 60s.
> chore: improve test execution speed

- benchmarks/pom.xml
- google-cloud-spanner/pom.xml
- pom.xml
- samples/install-without-bom/pom.xml
- samples/native-image/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
Updates all pending dependencies from #451
> deps: update all dependencies

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncAPITest.java
> chore: unflake ITAsyncAPITest.invalidDatabase

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
> chore: unflake blockAndTimeoutOnPoolExhaustion_withAcquireSessionTimeout

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetrySpanTest.java
> chore: unflake OpenTelemetrySpanTest.transactionRunnerWithFailedAndBeginTransaction

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
> chore: unflake asyncTransactionManagerWaitsUntilAsyncBatchUpdateHasFinished

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
> chore: unflake AsyncTransactionManagerTests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
DecodeMode.DIRECT should be the default mode for decoding rows.
> fix: make DecodeMode.DIRECT the default

- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ErrorHandler.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResumableStreamIterator.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/RetryOnDifferentGrpcChannelErrorHandler.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/RetryOnDifferentGrpcChannelException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnDifferentGrpcChannelMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
Adds an experimental error handler that retries RPCs that fail with DEADLINE_EXCEEDED on a different gRPC channel.
> chore: add experimental feature for retrying on different gRPC channel

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStreamIterator.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsChannelShutdownException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/CloseSpannerWithOpenResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
Adds the possibility to keep track of all running queries and cancel these when the client is closed. This option is currently only used for queries that are started by `BatchReadOnlyTransaction`s, as these do not use pooled sessions. Queries that use pooled sessions are automatically cancelled when the client is closed, because the sessions are deleted.
> feat: add option for cancelling queries when closing client

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStruct.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DecodeModeTest.java
Using one of the options DecodeMode.LAZY_PER_ROW or DecodeMode.LAZY_PER_COLUMN in combination with multi-threaded access to the ResultSet could lead to ClassCastExceptions, as the underlying decode methods were not synchronized. This could lead to multiple threads trying to access either the raw proto data or the decoded data at the same time, and expecting to get the other type of data.
> fix: synchronize lazy ResultSet decoding

- .github/workflows/hermetic_library_generation.yaml
Hi! I'm Diogo from Google's Open Source Security Team([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)) and I'm dropping by to suggest this small change that will enhance the security of your repository by preventing script injection attacks through your GitHub workflows.
In the piece of code I changed, you were directly using the value of a variable that comes from a user's input, so a malicious user could exploit that input and use it to run arbitrary code. By using an intermediate environment variable, the value of the expression is stored in memory, used as a variable and doesn't interact with the script generation process. This mitigates the script injection risks and also keeps your workflow running exactly as before. …
> fix: github workflow vulnerable to script injection

- samples/snippets/src/main/java/com/example/spanner/SpannerGraphSample.java
> docs: change the example timestamps in Spanner Graph java sample code

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java
The multiplexed session maintainer used a ScheduledExecutorService with a core pool size of zero. This can cause high CPU usage on Java 8 due to https://bugs.openjdk.org/browse/JDK-8129861. Also on higher versions of Java, it is better to use an executor with at least one core thread, instead of letting the executor create a new thread every time a task needs to be executed.
Fixes #3313
Fixes https://github.com/GoogleCloudPlatform/pgadapter/issues/2249
Fixes https://github.com/googleapis/java-spanner-jdbc/issues/1736
> fix: use core pool size 1 for maintainer

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
For regular sessions we maintain session to channel affinity. However, for multiplexed sessions we will need transaction to channel affinity.
This PR adds support for passing transaction channel hint for R/W transactions. This is needed to support multiplexed sessions in RW transactions. Without this change there will be impact on RW latencies.
> chore(spanner): support transaction channel hint for RW mux

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
This PR adds a package protected setter that can be used to enable/disable multiplexed sessions for R/W operations. This method will be used internally for testing purposes.
> chore(spanner): add package protected setter to enable mux for RW

- .github/workflows/hermetic_library_generation.yaml
This inlines the `repo.full_name` as an env var when checking if the PR is coming from a fork in order to prevent script injections.
> chore: fix hermetic_library_generation fork check

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementValueConverters.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutorImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RpcPriorityConverterTest.java
The Connection API used the (proto) enum Priority internally, while the actual connection property uses the public-facing
`com.google.cloud.spanner.RpcPriority` in public APIs. This change modifies the internal parser to also directly use the public-facing enum, instead of going through the proto enum definition first, only to translate to the public enum at a later moment.
> refactor: use RpcPriority internally in the Connection API

- samples/snippets/src/main/java/com/example/spanner/CreateInstanceExample.java
- samples/snippets/src/main/java/com/example/spanner/UpdateInstanceExample.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
> chore(samples): add sample for spanner editions

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/CloseSpannerWithOpenResultSetTest.java
The test uses a trick in the mock server, where the mock server is requested to freeze after returning the first row. However, when the mock server adds the first row to the stream, it is not guaranteed to be readable for the client, which again causes the test to hang on the ResultSet#next() call. The gRPC libraries then execute keep-alive requests to keep the TCP connection alive while waiting for data from the mock server, which will never come. This caused the query to eventually fail with a RESOURCE_EXHAUSTED error.
The tests work around this issue by just ignoring the case when the mock server fails to return the first row, as it is something that only very sporadically happens.
Fixes #3328
> test: ignore if the mock server failed to return a row

- README.md
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/CloseSpannerWithOpenResultSetTest.java
> test: try to consume rows until failure

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInOpenTelemetryMetricsProvider.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/CompositeTracer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
This PR fixes the below issues for client metrics.
- Use correct project id instead of defaultProjectId
- Sets a default value for directpath_enabled attribute 
- Use map overload for addAttributes in compositeTracer
> chore: fix built in client metric data

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionProperties.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
By default, EndToEndTracing is disabled from backend.
This PR adds enableEndToEndTracing Boolean connection option for implementing opt-in feature for EndToEndTracing.
Example URL: cloudspanner:/projects/test-project-123/instances/test-instance-123/databases/test-database-123?enableEndToEndTracing=true
Note: You can also pass in enableEndToEndTracing=false, but that is the default behaviour (even if you do not pass in this option).
> feat: Enabling endToEndTracing support in Connection API

- README.md
- samples/snippets/src/main/java/com/example/spanner/TracingSample.java
> docs: fix tracing sample to exit when completed, and use custom monitored resource for export

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
This PR enables client built-in metrics as default. 
Client built-in metrics support was added in PR https://github.com/googleapis/java-spanner/pull/3346
Below 4 metrics are introduced with this feature. 
- spanner.googleapis.com/client/operation_count
- spanner.googleapis.com/client/operation_latencies
- spanner.googleapis.com/client/attempt_count
- spanner.googleapis.com/client/attempt_latencies
To opt-out from client metrics 
```
Spanner spanner =
SpannerOptions.newBuilder()
.setProjectId("test-project")
.setBuiltInMetricsEnabled(false)
.build()
.getService();
```
Other related PRs
https://github.com/googleapis/java-spanner/pull/3359
https://github.com/googleapis/java-spanner/pull/3357
https://github.com/googleapis/java-spanner/pull/3346 …
> feat: client built in metrics

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterUtils.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterTest.java
This PR does two things 
1) Skip export if instance id is null
2) Update the IAM error message to add public documentation link
> fix: Client built in metrics. Skip export if instance id is null

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientMockServerTest.java
In a read-write transaction using a multiplexed session with (read/query + mutation) operations, the CommitResponse from the backend during the commit RPC may include a `MultiplexedSessionRetry` field (indicated by a precommit token). This field signals that the commit RPC should be retried once using the new precommit token. During this retry, mutations should not be resent, as they were already buffered in spanFE during the initial commit RPC call.
> chore(spanner): handle commit retry protocol extension for mux rw

- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
In some cases, the exception message is `null`, making it difficult to trace the origin of the exception. Printing the stack trace along with the message provides valuable context and helps identify the source of the exception.
b/371117430
b/377540961
> chore(executor): print stack trace for exceptions

- generation_config.yaml
> chore(spanner): fix EOL in spanner documentation

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInOpenTelemetryMetricsProvider.java
This PR calls Meter provider shutdown method when the client is shutdown to clean up the resources and export the remaining metrics data.
> fix: shutdown built in metrics meter provider

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- Removes some unused code.
- Fixes a few warnings.
> chore: remove unused code and fix some warnings

- google-cloud-spanner-executor/pom.xml
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java
- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
- samples/snippets/src/main/java/com/example/spanner/AddAndDropDatabaseRole.java
- samples/snippets/src/main/java/com/example/spanner/PgSpannerSample.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/AddAndDropDatabaseRole.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/CreateSequenceSample.java
- samples/snippets/src/main/java/com/example/spanner/admin/archived/PgSpannerSample.java
- samples/snippets/src/test/java/com/example/spanner/CreateIncrementalBackupScheduleSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/CreateInstancePartitionSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/DatabaseRolesIT.java
- samples/snippets/src/test/java/com/example/spanner/SampleTestBaseV2.java
- samples/snippets/src/test/java/com/example/spanner/SpannerGraphSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/admin/archived/CustomInstanceConfigSampleIT.java
- samples/snippets/src/test/java/com/example/spanner/admin/archived/DatabaseRolesIT.java
- samples/snippets/src/test/java/com/example/spanner/admin/archived/PgSpannerSampleIT.java
> ci(spanner): Fix nightly job issues

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
Reset the default to using a platform thread for connections. This was the default before adding an option for setting the executor type, and the new default is causing problems with the async Connection API.
Fixes #3541
> chore: reset default to platform thread

- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
> ci(spanner): improve performance of samples tests

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
Tries to unflake the `RetryOnInvalidatedSessionTest`. The setup logic was wrong, potentially causing a Spanner instance to be created with the wrong options, which again could cause tests to fail.
Fixes #3557
> test: unflake RetryOnInvalidatedSessionTest

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerErrorInterceptor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IsRetryableInternalErrorTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryableInternalErrorTest.java
Some specific internal errors should be retrid. Instead of adding INTERNAL
as a standard retryable error code, we use an interceptor to catch and
translate those specific errors.
See also b/375684610
> fix: retry specific internal errors

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Native metrics were automatically disabled when the emulator is used, but some clients (e.g. PGAdapter) set up the connection to the emulator manually instead of setting the environment variable. Also, when using in-mem mock servers, native metrics should be disabled, as they cannot be exported.
This PR therefore adds an additional check that disables native metrics when the client uses a NoCredentials instance.
> chore: disable native metrics when there are no credentials

- google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
There are SPANNER_SYS tables that contain ARRAY<STRUCT> columns. Adding support for this in the CloudClientExecutor so that queries involving these tables do not throw an error.
> feat: add support for ARRAY<STRUCT> to CloudCilentExecutor

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
This PR fixes the max_in_use_session value. Currently this value is only reset at client initialization.
> fix: update max_in_use_session at 10 mins interval

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceWrapper.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
This PR adds `db.name`,  `instance.name`, `db.table` attributes for all relevant Spans
> feat: Improve tracing by adding attributes

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
In a case where the following happens, the session that was used by an AsyncTransactionManager would not be returned to the pool:
1. The transaction is abandoned without a Commit or Rollback call.
2. The AsyncTransactionManager then executes a RollbackAsync internally.
3. If the internal RollbackAsync failed, then the session would not be closed.
> fix: AsyncTransactionManager did not always close the session

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/TransactionRunnerImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/UnitOfWork.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RunTransactionMockServerTest.java
Adds a `runTransaction` method to `Connection` to allow applications to execute read/write transactions that are automatically retried in the same way as in the standard client library. This feature will be extended to the JDBC driver, so transaction retries can be defined using a runner there as well.
> feat: add transaction runner for connections

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStreamIterator.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResumableStreamIterator.java
> chore(spanner): unflake unit tests

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionProperties.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
> feat(spanner): mTLS setup for spanner external host clients

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
> feat: add LockHint feature

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
> fix(spanner): moved mTLSContext configurator from builder to construtor

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Adds support for GRAPH and pipe-syntax queries to the Connection API. This will make these types of queries usable in the JDBC driver.
This also fixes an issue with regular GoogleSQL queries that start with a bracket. These queries were not correctly recognized as valid queries.
> feat: support graph and pipe queries in Connection API

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContext.java
Clarify how async update statements can overtake each other on the network, and how this means that multiple async updates should preferably block for a result to be returned before sending the next one.
> docs: clarify how async updates can overtake each other

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterTest.java
The instance-id was only added for built-in metrics when the headers of the request was sent. This meant that any request that would NOT get sent would not include an instance-id, which again would cause the export of ALL built-in metrics to stop. This would happen because the metric without an instance-id would remain in the collected metrics.
A request would get into this state if the client ran into a network issue that would prevent the client from making a network connection to Spanner.
Fixes #3611
> fix: always add instance-id for built-in metrics

- samples/snippets/src/main/java/com/example/spanner/ChangeStreamsTxnExclusionSample.java
- samples/snippets/src/test/java/com/example/spanner/ChangeStreamsTxnExclusionSampleIT.java
Add samples and IT tests on setting `Options.excludeTxnFromChangeStreams()` in various write requests. This is a follow up after  https://github.com/googleapis/java-spanner/pull/2959
> docs(samples): add samples and tests for change streams transaction exclusion

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Reverts googleapis/java-spanner#3629
Reverting to further debug where the sapns are ending. Will reopen if I feel this change is needed.
> Revert "fix(spanner): end spans for read-write methods"

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
The `close()` method in `TransactionManager` was only being called when used within a `try-with-resources` block, as `TransactionManager` implements `AutoCloseable`.  
However, in cases where `try-with-resources` was not used or `.close()` was not explicitly called, `close()` was never invoked, leading to resource leaks—such as spans not being closed properly. This is particularly an issue in JDBC, where `try-with-resources` cannot be used.  
This PR ensures that `close()` is implicitly invoked whenever the transaction reaches an end state, preventing resource leaks.
> fix(spanner): release resources in TransactionManager

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AutoCommitMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AutocommitDmlModeTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RetryDmlAsPartitionedDmlMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SingleUseTransactionTest.java
- Adds an option to indicate that a statement is the last in a read/write transaction. This option should only be set for the last statement before committing the transaction. Trying to execute any other statements after this statement will result in an error.
- The `last_statement` option is automatically set for statements that are executed in autocommit mode in the Connection API. This option will also automatically be set for statements executed on a JDBC connection in autocommit mode.
cc @sgorse123
> feat: add option to indicate that a statement is the last in a transaction

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/XGoogSpannerRequestId.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/XGoogSpannerRequestIdTest.java
This change adds in the bases to bring in the functionality for the "x-goog-spanner-request-id" that'll be used for debugging without the limits of trace continuity and sampling.
Updates #3537
> chore(x-goog-spanner-request-id): commit foundation

- .github/CODEOWNERS
- .repo-metadata.json
- generation_config.yaml
> chore(spanner): Update codeowner team to TeamSync managed team

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionProperties.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ExperimentalHostMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
Ensure multiplexed sessions are used when client is connecting to an experimental host
> chore: enable multplexed sessions for experimental host

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractMultiplexedSessionDatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionTest.java
Get the database dialect using the multiplexed session that is created by the client when multiplexed sessions are enabled. This prevents unnecessarily creating a regular session when MinSessions has been set to zero and multiplexed sessions have been enabled.
> perf: get database dialect using multiplexed session

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementTimeoutTest.java
Adds a global timeout that is applied to each of the tests in StatementTimeoutTest. This ensures that if any of the tests are slow, the test case will fail.
Also cleans up some warnings and removes some old-style assertions.
> test: fail the StatementTimeoutTest if any of the tests are slow

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/GrpcStreamIterator.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
Fixes: b/394475581
gRPC trailers are headers which is usually sent after all the messages are sent by the server in the stream. Trailers usually causes additional latency of 250-300 μs after last message is sent in the stream. From the server, we will receiving last field which tells us about last PartialResultSet and we no longer will be waiting for trailers to assume that all the messages are received.
> perf: Skip gRPC trailers for StreamingRead & ExecuteStreamingSql

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplWithDefaultRWTransactionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplWithTransactionOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerTestActions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerTestUtil.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadWriteTransactionWithInlineBeginTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Isolation level support added in various write APIs:
```
write
writeWithOptions
writeAtleastOnceWithOptions
readWriteTransaction
transactionManager
transactionManagerAsync
runAsync
```
Note: Samples and integration tests will be added in separate PRs.
> feat: support isolation level REPEATABLE_READ for R/W transactions

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadAsyncTest.java
Make the expected exception sticky, so that the exception is not cleared if the RPC is retried due to a transient `UNAVAILABLE` error.
> test: unflake ReadAsyncTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
Cleans up some warnings and a leaked thread that was not stopped in one of the tests. The actual flaky test was probably fixed as part of the refactor of async queries, and is no longer reproducible.
Closes #3365
> test: cleanup AsyncResultSetImplTest

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Unflake InlineBeginTransactionWithoutExecutorTest by not resetting the 'ignore-inline-begin' flag after the first request. This prevents retried requests from first clearing the flag and then getting the unexpected behavior during the retry.
Fixes #3552
> test: unflake InlineBeginTransactionWithoutExecutorTest

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DelayedMultiplexedSessionTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientMockServerTest.java
Before this change, when a transaction using a multiplexed session encountered an `UNIMPLEMENTED` error with the message `Transaction type read_write not supported with multiplexed sessions` from the backend, the transaction would fail abruptly without any special handling.
This PR introduces handling for this scenario in the `TransactionRunner`, where transactions encountering the `UNIMPLEMENTED` error with the message `Transaction type read_write not supported with multiplexed sessions` are automatically retried using a regular session.
> chore: retry in-flight transactions on regular sessions when multiplexed sessions encounter UNIMPLEMENTED errors

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchTransactionId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClientMockServerTest.java
If PartitionQueryRequest or PartitionReadRequest with multiplexed session return unimplemented error, then an implicit fallback to regular session will occur.
> chore: fallback for Partitioned Operations with multiplexed session

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutorImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/TransactionMockServerTest.java
The `set transaction isolation level` SQL statement was accepted by a connection, but did not actually set the isolation level.
> fix: set transaction isolation level had no effect

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
The PR adds default implementation for following methods of AbstractStructReader.
getIntervalInternal
getIntervalListInternal
> fix: add default implementations for Interval methods in AbstractStructReader

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerBatchUpdateException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionMutationLimitExceededException.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RetryDmlAsPartitionedDmlMockServerTest.java
If a DML batch fails due to a TransactionMutationLimitExceededException, then add that specific exception as the cause to the SpannerBatchUpdateException. This makes it easier to detect this specific error, and potentially retry the individual statements as PDML.
> feat: add TransactionMutationLimitExceededException as cause to SpannerBatchUpdateException

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Statement.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/PostgreSQLStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerStatementParser.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserBenchmark.java
This fixes a performance bottleneck I noticed while profiling pgadapter under a TPCC workload.
```
Benchmark                                Mode  Cnt       Score      Error  Units
StatementParserBenchmark.isQueryTest    thrpt    5  475330.395 ± 2522.511  ops/s
StatementParserBenchmark.longDmlTest    thrpt    5    3611.682 ±   58.704  ops/s
StatementParserBenchmark.longQueryTest  thrpt    5    5015.354 ±    8.138  ops/s
```
```
Benchmark                                Mode  Cnt       Score       Error  Units
StatementParserBenchmark.isQueryTest    thrpt    5  338079.227 ± 26995.410  ops/s
StatementParserBenchmark.longDmlTest    thrpt    5    1153.123 ±     5.604  ops/s
StatementParserBenchmark.longQueryTest  thrpt    5    2011.550 ±    72.433  ops/s
```
> perf: optimize parsing in Connection API

- README.md
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
The HeaderInterceptor creates a key consisting of the database name and method name that is used for OpenTelemetry attributes and metrics. The number of unique keys is low. However, the key is constructed from the DatabaseName and method name every time, which leads to a lot of string creation:
1. The DatabaseName.toString() method is called every time. This constructs a new string.
2. The result of DatabaseName.toString() is concatenated with the methodName to create yet another string.
Instead of creating the key every time, we can cache the key values without doing the string creation and concatenation every time.
> perf: cache the key used for OTEL traces and metrics

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsConstant.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsRecorder.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsTracer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/CompositeTracer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerMetadataProvider.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractNettyMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/SpannerMetadataProviderTest.java
Reverts googleapis/java-spanner#3724
> Revert "feat: built in metrics for afe latency and connectivity error"

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractBaseUnitOfWork.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementBeginExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementExplainExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementPartitionExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementPgBeginExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementRunPartitionExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementRunPartitionedQueryExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementSetExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutor.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutorImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DmlBatch.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SimpleParser.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ClientSideStatementsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionStatementWithOneParameterTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlBatchTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlClientTests.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DmlBatchTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadOnlyTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SetPgSessionCharacteristicsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SingleUseTransactionTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Calls to getSqlWithoutComments() have been replaced with calls to getSql(). This reduces the number of times that the SQL string needs to be parsed, and the number of strings that are created by the Connection API.
The only part of the Connection API that still depends on the SQL string without comments, is the check whether a DML statement contains a THEN RETURN / RETURNING clause. This will be removed in a follow-up change.
> perf: remove all calls to getSqlWithoutComments

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerTypeConverter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Statement.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
Currently Spanner Client Library doesn't support passing positional (or unnamed) parameters while creating the statement. This feature provides the support for unnamed parameters which helps customers to create SQL Statement with unnamed parameter(?)
> feat: support unnamed parameters

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsConstant.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsProvider.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterUtils.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBuiltInMetricsTest.java
This PR adds below GRPC Metrics available for Spanner Engineers. 
These metrics are disabled as default currently. To enable set `SPANNER_DISABLE_DIRECT_ACCESS_GRPC_BUILTIN_METRICS=false` 
- grpc.lb.rls.default_target_picks
- grpc.lb.rls.target_picks
-   grpc.xds_client.server_failure
-   grpc.xds_client.resource_updates_invalid
-   grpc.xds_client.resource_updates_valid
> feat: [Internal] open telemetry built in metrics for GRPC

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
Closing a pooled session multiple times would cause it to be added to the pool multiple times. This fix prevents this by keeping track of the state of a session that has been checked out.
> fix: only close and return sessions once

- google-cloud-spanner/clirr-ignored-differences.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsRecorder.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsTracer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/CompositeTracer.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractNettyMockServerTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
Currently the Java implementation only parses the [integer part](https://github.com/googleapis/java-spanner/blob/32b2373d62cac3047d9686c56af278c706d7c488/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java#L79).
According to the w3c standard, this should be a float (https://www.w3.org/TR/server-timing/#duration-attribute).
> fix: change server timing duration attribute to float as per w3c

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java
Enable gRPC/AFE built-in metrics if:
1. The env var SPANNER_DISABLE_DIRECT_ACCESS_GRPC_BUILTIN_METRICS / SPANNER_DISABLE_AFE_SERVER_TIMING is explicitly set to "false", OR
2. DirectPath is enabled AND the env var is not set to "true". This allows metrics to be enabled by default when DirectPath is on, unless explicitly disabled via env.
This PR also skips GFE metrics when DirectPath is used.
> feat: enable AFE and gRPC metrics for DP

- .kokoro/presubmit/samples.cfg
- README.md
- samples/snippets/src/main/java/com/example/spanner/DatabaseAddSplitPointsSample.java
- samples/snippets/src/main/java/com/example/spanner/UnnamedParametersExample.java
- samples/snippets/src/test/java/com/example/spanner/UnnamedParametersIT.java
> docs: Add samples for unnamed (positional) parameters

- .kokoro/presubmit/graalvm-native-a.cfg
- .kokoro/presubmit/graalvm-native-b.cfg
- .kokoro/presubmit/graalvm-native-c.cfg
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITUuidTest.java
> ci: Fix UUID tests which is failing in cloud-devel

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlClient.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlTest.java
The Connection API should automatically remove any trailing semicolons in DDL statements. Spanner accepts trailing semicolons in queries and DML statements, but not in DDL statements. Previously, the Connection API would remove all comments and trailing semicolons from DDL statements. Comments are now supported in DDL statements, and are therefore no longer removed by the Conneciton API, but that change also unintentionally kept any trailing semicolons in the SQL string that is sent to Spanner.
Fixes https://github.com/cloudspannerecosystem/liquibase-spanner/issues/481
> fix: remove trailing semicolons in DDL

- benchmarks/pom.xml
- benchmarks/src/main/java/com/google/cloud/spanner/benchmark/AbstractRunner.java
- benchmarks/src/main/java/com/google/cloud/spanner/benchmark/BenchmarkRunner.java
- benchmarks/src/main/java/com/google/cloud/spanner/benchmark/BenchmarkingConfiguration.java
- benchmarks/src/main/java/com/google/cloud/spanner/benchmark/JavaClientRunner.java
- benchmarks/src/main/java/com/google/cloud/spanner/benchmark/LatencyBenchmark.java
Following features are added
1. Support running benchmarking for specific time(30m)
2. Support running warm up before running benchmarking
3. Support staleness
4. Support running reads
> chore: update benchmarking script

- samples/snippets/src/test/java/com/example/spanner/DatabaseAddSplitPointsIT.java
Currently there's an open issue where on database deletion split points quota should be reclaimed. Currently it's not happening. There's a limitation of 50 split points can be added in an instance. 
> ci: disable split points IT

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
Ensure multiplexed sessions are used when client is connecting to an experimental host using PGAdapter - by passing additional parameter -r "isExperimentalHost=true"
> chore: enable experimentalHost support for pgAdapter

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/XGoogSpannerRequestId.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTests.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/XGoogSpannerRequestIdTest.java
This change plumbs x-goog-spanner-request-id into BatchCreateSessions and asserts that the header is present for that method.
Updates #3537
> chore(x-goog-spanner-request-id): plumb for BatchCreateSessions

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Same as #3645 that was reverted earlier. The Cloud Spanner backend is now able to process the bound token if sent.
> feat: enable ALTS hard bound token in DirectPath

- samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
The snippet shows how Repeatable Read can be configured at client and transaction level.
User can try the new snippet by: (1) createdatabase (2) write (3) isolationlevelsettings.
> docs: Add snippet for Repeatable Read configuration at client and transaction

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerException.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
Enable asserting that all the Spanner Method RPCs have
x-goog-spanner-request-id.
Updates #3537
> chore(x-goog-spanner-request-id): enable tests for more RPCs

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/MergedResultSet.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/MergedResultSetTest.java
Queries that use the PartitionedQuery API in combination with DataBoost can return completely empty result sets (no results and no metadata) for some partitions. The MergedResultSet should ignore these result sets and not use them as the source of metadata for the merged result.
> fix: return non-empty metadata for DataBoost queries

- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ITTransactionRetryTest.java
In this PR, we will be adding an Integration test in which we will check if `google.rpc.retryinfo-bin` is sent in the trailers when two transactions tries to modify the same row. 
1. gRPC request should fail with aborted error for the second transaction
2. gRPC trailers should contain the retryinfo trailer and delay
> ci: Add tests for retry_info trailer

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
> chore: bump the max inbound message size from GRPC's default 4MB

- .github/scripts/update_generation_config.sh
- .github/workflows/update_generation_config.yaml
Unfortunately, https://github.com/googleapis/sdk-platform-java/pull/3853 cannot be automatically propagated. 
This PR manually updates this script with the latest.
Confirmed in https://github.com/googleapis/java-spanner/actions/runs/16505320896
> chore: manual update of update_generation_config.sh

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
The `Value#hashCode()` method threw a NullPointerException for untyped values.
> fix: potential NullPointerException in Value#hashCode

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/BuiltInMetricsProvider.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionProperties.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerCloudMonitoringExporterTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
This PR adds the support for configuring Partner Universe(TPU) in Java Spanner Client Library.
* Decides the monitoring host based on universeDomain set in SpannerOptions
* Decides the default host in SpannerOptions based on universeDomain
* Provides support for universeDomain in ConnectionProperties(JDBC)
* Removes the existing `setMonitoringHost` method which is no longer needed. TPC is not live yet so this functionality was not used.
> feat: TPC support

- google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/LocalConnectionChecker.java
Check and return early if the host is null or empty.
> fix: potential NullPointerException in LocalConnectionChecker

- .github/workflows/update_generation_config.yaml
- google-cloud-spanner/pom.xml
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerCloudMonitoringExporter.java
- google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/benchmarking/BenchmarkValidator.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/benchmarking/MonitoringServiceImpl.java
- google-cloud-spanner/src/test/java/com/google/cloud/spanner/benchmarking/ReadBenchmark.java
- google-cloud-spanner/src/test/resources/com/google/cloud/spanner/jmh/jmh-baseline.json
This PR introduces a framework for performance regression testing in the Java Spanner client library using JMH (Java Microbenchmark Harness), as outlined in our internal design document for performance regression detection.
**Key Changes:**
*   **JMH Benchmarks:** Includes initial JMH benchmark classes targeting key read operations:
*   `google.spanner.v1.Spanner/StreamingRead`
*   `google.spanner.v1.Spanner/ExecuteStreamingSql`
*   **Mock Server Integration:** The benchmarks are designed to run against a local mock gRPC Spanner server to ensure consistent results and isolate client library performance.
*   **Runner Script:** A shell script is provided to orchestrate the benchmark execution, including setup, warm-up, execution, and result collection. [cl/811649110](http://cl/811649110) …
> ci: Design and implement a comprehensive performance regression presubmit/continuous job
