pom.xml
=> deps: keep OpenCensus at 0.24.0 until gRPC updates

pom.xml
=> fix: use grpc 1.27.2 to prevent version conflicts

proto-google-cloud-spanner-admin-database-v1/clirr-ignored-differences.xml, proto-google-cloud-spanner-admin-instance-v1/clirr-ignored-differences.xml
Adds generic ignore rules for added methods to interfaces in the generated code.
Fixes #99
=> fix: ignore added interface methods for generated code

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java
Adds integration test cases for VPC-SC.
=> test: add VPC-SC test cases for backups

google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTest.java
Adds an additional test case for the `SessionClient` to verify the following behavior:
* Calling `SessionClient#asyncBatchCreateSesions` with `distributeOverChannels=false` should execute only one RPC using one channel.
* Calling `SessionClient#asyncBatchCreateSesions` with `distributeOverChannels=false` multiple times, should use a new channel hint for each consecutive call.
This ensures that increasing the number of sessions in the pool using consecutive calls to this method will eventually distribute the sessions over all available channels.
=> tests: add test for session distribution

google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
Increase the test timeout to prevent flaky failures. Also removes all warnings regarding the deprecated ExpectedException class.
Fixes #158
=> fix: increase test timeout and remove warnings

pom.xml, samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml
=> samples: fix samples library versions

.readme-partials.yaml, .repo-metadata.json, README.md, synth.metadata, synth.py
This should keep the libraries-bom version up to date and standardize the README structure.
Fixes #168
=> chore: generate README from synth.py

google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
=> tests: fix flaky restoreTestDatabase failures

google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
=> tests: increase timeout to prevent flakiness

google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Enables all integration tests to be executed against the emulator, unless the integration test uses features that are explicitly not supported by the emulator.
=> tests: enable integration tests with the emulator

README.md
Originates from https://github.com/googleapis/java-spanner/issues/53#issuecomment-628111904
This is just the initial draft, will update after #128.
Feel free to add comments.
=> chore: document OpenCensus Metrics

google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
=> tests: prevent multiple retries quickly after each other

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
=> test: unskip tests passing against the emulator

google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Seen here: https://github.com/googleapis/java-spanner/pull/294/checks?check_run_id=797447151
=> tests: fix flaky instance admin test

google-cloud-spanner/pom.xml, pom.xml
Remove specific versions of Maven plugins from pom and update shared config to 0.9.2.
=> deps: update shared config to 0.9.2

git-hooks/pre-commit
Adds git pre-commit hook to check for code formatting. This will prevent commits to be done if the formatting fails.
=> refactor: adds git pre-commit hook

git-hooks/pre-commit
Checks for clirr errors on the pre-commit hook.
=> feat: adds clirr check on pre-commit hook

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Adds integration tests for `NUMERIC` data type.
=> test: add integration tests for numeric

README.md
Based on https://github.com/googleapis/java-spanner/pull/128
=> chore: fix OpenCensus metrics list

.github/CODEOWNERS, .repo-metadata.json
Adds the group api-spanner-java as codeowners.
=> chore: adds api-spanner-java group as codeowners

google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Allow a partial statement to be registered as the key for a statement result on the mock server. This makes it easier to mock results for statements that are generated by a framework with random or time based values, as only the first (static) part of the statement needs to be registered on the mock server.
Fixes this TODO: https://github.com/cloudspannerecosystem/liquibase-spanner/blob/31c04dcaeb8105009774a51cf41a1a10bc1c6685/src/test/java/com/google/cloud/spanner/TempMockSpannerServiceImpl.java#L188
=> test: allow partial statements on the mock server

samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml, samples/snippets/src/main/java/com/example/spanner/AddNumericColumnSample.java, samples/snippets/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java, samples/snippets/src/main/java/com/example/spanner/CreateInstanceExample.java, samples/snippets/src/main/java/com/example/spanner/QueryWithNumericParameterSample.java, samples/snippets/src/main/java/com/example/spanner/SpannerSample.java, samples/snippets/src/main/java/com/example/spanner/UpdateNumericDataSample.java, samples/snippets/src/test/java/com/example/spanner/AsyncExamplesIT.java, samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java, samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java, samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Syncs the samples of this repository with the samples in the https://github.com/GoogleCloudPlatform/java-docs-samples repository.
=> chore: updates samples

google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
Adds an additional test case for inlined begin transaction when the first statement is a query. Queries are executed using executeStreamingSql, and if the stream is broken, the original RPC is retried with a resume code. That retry should not include a BeginTransaction option when the transaction has already been initialized by the first RPC.
=> test: test stream retries in combination with inlined begin

CHANGELOG.md
Happening in versions >= 3.0.0 and <= 3.3.1.
=> chore: warns of transactions bug

google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
Remove write fraction parameter from `SessionPoolStressTest` as it is no longer in use.
=> test: remove write fraction from test

google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Skips tests for DEADLINE_EXCEEDED errors for non-idempotent methods as they won't retry anyways. Speeds up test execution with approx 2 seconds.
=> test: skip timeout tests for non-idempotent methods

google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
The SingleUseTransaction in the Connection API previously used a TransactionManager instead of a TransactionRunner, as this was the only way that it was possible to implement a statement-specific timeout. This is now supported by the client library, and the SingleUseTransaction had already been moved to using only a TransactionRunner. There was however still an unused TransactionManager reference in
the code.
Fixes #852
=> cleanup: remove unused transaction manager

README.md
=> docs: libraries-bom 16.4.0

google-cloud-spanner-bom/pom.xml, google-cloud-spanner/clirr-ignored-differences.xml, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerApiFuturesTest.java, pom.xml
Configures source / target compilation to be Java 8.
=> chore: configures project pom to java 8

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
=> test: add additional logging to backup pagination test

google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Adds an additional test case for DatabaseClients that have been invalidated. These should continue to return the ResourceNotFoundException even after they have been invalidated.
=> test: add additional test case for invalidated db clients

samples/snippets/src/test/java/com/example/spanner/EncryptionKeyIT.java
The backup operations can still fail because of too many pending operations. It would retry 10 times with waiting 60 seconds between each attempt, but that does not seem to be enough. The max attempts has therefore been increased to 20 and better logging has been created by throwing a custom exception when it happens. The previous log was not visible, because the sample runners are redirecting the standard out to a string.
Fixes #1019
=> test: retry backup operation 20 times

google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Allows setting a custom user agent in any case, instead of only in lower case.
=> fix(4.0.x): allows setting custom user agent in any case

google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Allows setting a custom user agent in any case, instead of only in lower case.
=> fix(5.2.x): allows setting custom user agent in any case

google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Adds test for setting a custom user agent header.
=> test(3.1.x): adds test for setting custom user-agent

google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
The begin() call should be before the retry loop, and not inside. The catch clause for an AbortedException should reset the transaction manager and assign the new transaction context to the original transaction context variable.
Fixes #1125
=> test: move begin() outside retry loop

google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Allows setting a custom user agent in any case, instead of only in lower case.
=> fix(3.3.x): allows setting custom user agent in any case

.github/workflows/ci.yaml, .github/workflows/integration-tests-against-emulator.yaml
Configures CI for branch
Automatically generated PR for LTS
=> chore(3.3.3-sp): configure initial sp version

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPitrUpdateDatabaseTest.java
=> test: increase operation timeout to prevent flaky failures

google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
Wait with the commit call until we know for sure that the transaction has been aborted.
Fixes #1198
=> test: await commit until tx is aborted

google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
=> test: empty queue before check to prevent flaky failures

samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
Adds samples for client with query options and query with query options specifying the optimizer statistics package.
=> samples: add samples for statistics package

.github/workflows/ci.yaml, .github/workflows/integration-tests-against-emulator.yaml
=> feat: configure initial sp version

.github/release-please.yml, .github/sync-repo-settings.yaml
=> build: configure branch 6.4.4-sp as a release branch

.kokoro/build.sh, google-cloud-spanner/pom.xml
Trying out solution from https://stackoverflow.com/questions/21661559/maven-failsafe-plugin-hangs-unexpectedly
=> chore: fix failsafe plugin hanging

.github/release-please.yml
=> build: configure release-please should tag releases

google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
The trick that the SpanTest class does to change a private static final field
is no longer possible in JDK12 and higher. This test therefore needs to be
skipped when the tests are running on Java12 or higher.
Fixes the build error in #1462
=> test: skip SpanTest on JDK12 and higher

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPitrUpdateDatabaseTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java
Moves ITDatabaseAdminTests into the ITBackupTest which is only executed on the nightly build.
=> test: move backup tests into slow tests category

google-cloud-spanner/pom.xml, samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml
=> chore: move test instance to us-west1 region

google-cloud-spanner/pom.xml, samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml
Upgrades GSON dependency to 2.8.9
=> chore(deps): upgrade gson to 2.8.9

google-cloud-spanner/pom.xml
CC: @Neenu1995 @thiagotnunes 
Testing whether "deps" makes a release pull request.
=> deps: upgrade gson to 2.8.9

google-cloud-spanner/pom.xml, samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml
Bump OpenCensus version to 0.29.0.
=> deps: bump OpenCensus API to 0.29

google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/HeaderInterceptor.java
=> fix: Correct recording values in opencensus measureMap in HeaderInterceptor

google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
refactor: typo fix in maxSessions variable doc string.
=> refactor: typo fix in maxSessions variable doc string.

google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
=> test: Creating dummy spanner instance for ITInstanceAdminTest

README.md, samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
=> test: Deleting stale encrypted instances

.github/workflows/ci.yaml, .github/workflows/integration-tests-against-emulator.yaml
=> ci: configure the protected branch

.github/release-please.yml, .github/sync-repo-settings.yaml, README.md
=> chore: setting up 6.23.x branch

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: setting up 6.33.x branch

.kokoro/build.sh
=> chore: Updating instance name

.kokoro/build.sh, .kokoro/continuous/integration-cloud-devel.cfg, .kokoro/continuous/integration-cloud-staging.cfg, .kokoro/nightly/integration-cloud-devel.cfg, .kokoro/nightly/integration-cloud-staging.cfg
Adding new Kokoro configurations to run integration tests against staging and devel environment as part of nighly and continuous build.
=> chore: Adding Kokoro Configurations to run integration tests against staging and devel environment.

google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudUtil.java
=> Fix: update test certificate name.

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseRolePermissionTest.java
Use correct SpannerOptions from testHelper.
=> test: fix ITDatabaseRolePermissionTest.roleWithNoPermissions to use correct SpannerOptions

README.md, google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudClientExecutor.java
Fix a typo in executeCloudBatchDmlUpdates.
=> fix: update executeCloudBatchDmlUpdates.

README.md, google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudExecutor.java
=> fix: add error details for INTERNAL error

README.md, samples/snippets/src/main/java/com/example/spanner/BatchSample.java
Updating Batch Sample to add databoost
=> samples: Modifying BatchSample to add snippet with databoost

README.md, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseRolePermissionTest.java
* Parameterised the existing tests to support additional dialect `POSTGRESQL`.
=> test: fine grained access control for Postgres dialect.

google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
Reverts googleapis/java-spanner#2538
=> Revert "feat: Enable leader aware routing by default"

README.md, google-cloud-spanner/src/main/resources/META-INF/native-image/com.google.cloud.spanner/reflect-config.json
Follow-up to https://github.com/googleapis/java-spanner/pull/2617
=> chore: fix indentation in reflect-config.json file

README.md, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
There are additional optimisations added to support batch dml with a large batch size. These tests are added as part of an outage action item to test batch update against all environment.
=> test: add integration tests for large batch dml updates.

README.md, google-cloud-spanner-executor/pom.xml, google-cloud-spanner/pom.xml
=> chore: remove temp exclusion

README.md, google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AbstractStatementParser.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
=> chore: Include RENAME in DDL statement list

README.md, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITProtoColumnTest.java
This PR disables the integration tests of Proto Columns.
b/322553163
=> test: disable proto column tests

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: next release from main branch is 6.56.0

google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
- New implementations for multiplexed session have not been added in this PR to keep the diff small.
=> chore: generalise session pool class for multiplexed session.

.kokoro/nightly/integration-directpath-enabled.cfg, .kokoro/nightly/integration.cfg
=> ci: replace projectID for integration tests

google-cloud-spanner/clirr-ignored-differences.xml, google-cloud-spanner/src/main/java/com/google/cloud/spanner/Session.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
* prepareReadWriteTransactions() is deprecated and has no usages.
* the refactoring will help more refactoring that will be made in `SessionImpl` class for multiplexed session.
=> refactor: remove code related to prepareReadWriteTransactions.

.github/sync-repo-settings.yaml
=> chore: mark multiplexed session unit test as required

google-cloud-spanner/clirr-ignored-differences.xml, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
=> fix: make SessionPoolOptions#setUseMultiplexedSession(boolean) package private

.github/release-please.yml
=> chore: enable releases for 6.67.x branch

google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetrySpanTest.java
Add a wait for the BatchCreateSessions span, as that operation is executed asynchronously, and is not guaranteed to have finished when the transaction finishes. The reason for this is that the transaction only needs 1 session, while the operation creates 4 sessions, and the operation only finishes once all 4 sessions have been created.
Fixes #3152
=> chore: add wait for async span

google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
Remove some unused options and make some fields final.
=> chore: cleanup SessionPoolOptions

benchmarks/pom.xml, samples/native-image/pom.xml, samples/pom.xml
This PR groups the updates in 
* https://github.com/googleapis/java-spanner/pull/3103
* https://github.com/googleapis/java-spanner/pull/3118
* https://github.com/googleapis/java-spanner/pull/3074
* https://github.com/googleapis/java-spanner/pull/3072
* https://github.com/googleapis/java-spanner/pull/3071
* https://github.com/googleapis/java-spanner/pull/3069
* https://github.com/googleapis/java-spanner/pull/3178
=> deps: update dependencies

grpc-google-cloud-spanner-admin-database-v1/clirr-ignored-differences.xml
Fixes CLIRR failure in mainline https://github.com/googleapis/java-spanner/actions/runs/10050817564/job/27779375111
=> chore: skip clirr 7012 exceptions with grpc admin package

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: setup 6.66.x lts branch

.github/workflows/hermetic_library_generation.yaml
Definitive fix will be defined after solving comments in https://github.com/googleapis/java-bigtable/pull/2317
=> chore: temporary fix for hermetic library generation workflow

google-cloud-spanner-executor/src/main/java/com/google/cloud/executor/spanner/CloudExecutor.java
=> chore: append gRPC error message for debugging

google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
=> chore: check that the session has a lastUseTime

google-cloud-spanner/src/main/java/com/google/cloud/spanner/Instance.java
=> fix(spanner): getEdition() is returning null for Instance

.kokoro/build.sh, .kokoro/presubmit/integration-directpath-enabled.cfg
Fixes [#3165](https://github.com/googleapis/java-spanner/issues/3165)
=> chore(spanner): use different project for directpath presubmit integration tests

.kokoro/nightly/integration-directpath-enabled.cfg
=> chore(spanner): Fix permission issue in running nightly job

google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITAsyncTransactionRetryTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDmlReturningTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITFloat32Test.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITForeignKeyDeleteCascadeTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITJsonWriteReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITLargeReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPgJsonbTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPgNumericTest.java
Multiple tests were skipped on the Emulator, because the features that are covered by these tests were originally not supported on the Emulator. These features are now available on the Emulator, and the tests can be enabled.
=> test: enable more tests on the Emulator

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Enables a few tests that were disabled for PostgreSQL due to historical reasons (that are no longer valid).
=> test: enable write tests for PostgreSQL

google-cloud-spanner/src/main/java/com/google/cloud/spanner/MultiplexedSessionDatabaseClient.java, google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryApiTracerTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryBuiltInMetricsTracerTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionChannelHintTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
This PR fixes unit tests for multiplexed sessions read-write.
=> chore(spanner): fix unit tests for mux rw

.github/CODEOWNERS
=> chore(spanner):- Update CODEOWNERS

.kokoro/continuous/integration-cloud-devel-directpath-enabled.cfg, .kokoro/continuous/integration-cloud-staging-directpath-enabled.cfg, .kokoro/nightly/integration-cloud-devel-directpath-enabled.cfg, .kokoro/nightly/integration-cloud-staging-directpath-enabled.cfg, .kokoro/nightly/integration-directpath-enabled.cfg, .kokoro/presubmit/integration-directpath-enabled.cfg
=> ci(spanner): Enable directpath in Kokoko jobs

samples/snippets/src/main/java/com/example/spanner/CreateInstanceWithAutoscalingConfigExample.java
=> ci(spanner): Fix nightly samples job failure for creating managed autoscalar instance

samples/snippets/src/main/java/com/example/spanner/CreateInstanceWithAsymmetricAutoscalingConfigExample.java
=> ci(spanner): Fix sample tests related to asymmetric autoscaling

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 6.89.0

google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
=> fix: revert the ALTS bound token enablement

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDmlReturningTest.java
Fixes #3575
Fixes #3342
Fixes #3274
Fixes #3174
Fixes #3169
Fixes #3059
Fixes #3002
=> test: unflake ITDmlReturningTest

.kokoro/build.sh, .kokoro/presubmit/integration-directpath-enabled.cfg, .kokoro/presubmit/integration-multiplexed-sessions-enabled.cfg, .kokoro/presubmit/integration.cfg
=> ci: change presubmit jobs to run against cloud-devel

google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITEndToEndTracingTest.java
=> chore(spanner): fix tests

.kokoro/build.sh, .kokoro/presubmit/integration-directpath-enabled.cfg, .kokoro/presubmit/integration-multiplexed-sessions-enabled.cfg, .kokoro/presubmit/integration.cfg
Reverts googleapis/java-spanner#3811
=> Revert "ci: change presubmit jobs to run against cloud-devel"

google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
This removes an unnecessary non-ASCII Unicode character that was added in https://github.com/googleapis/java-spanner/commit/6e220ffd6c019436390f99df62060a1403be83ce#r156074934
Fixes #3843
=> fix: non-ASCII Unicode characters in code

.github/workflows/hermetic_library_generation.yaml, .github/workflows/samples.yaml, .github/workflows/unmanaged_dependency_check.yaml, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, .kokoro/presubmit/graalvm-native-c.cfg, benchmarks/pom.xml, generation_config.yaml, google-cloud-spanner-bom/pom.xml, google-cloud-spanner-executor/pom.xml, google-cloud-spanner/pom.xml, pom.xml, samples/install-without-bom/pom.xml, samples/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml
This pull request is generated with proto changes between [googleapis/googleapis@2eec62d](https://github.com/googleapis/googleapis/commit/2eec62dc7ed836c8d9f73fb313afb8f48c361bef) (exclusive) and [googleapis/googleapis@69d549c](https://github.com/googleapis/googleapis/commit/69d549c7eaccfc9584fd64c38c746a48ef635f60) (inclusive).
BEGIN_COMMIT_OVERRIDE
BEGIN_NESTED_COMMIT
fix(deps): update the Java code generator (gapic-generator-java) to 2.57.0
END_NESTED_COMMIT
END_COMMIT_OVERRIDE
=> chore(deps): update all deps

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: create LTS branch 6.95.x

google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/OpenTelemetryApiTracerTest.java
The AsyncTransactionManager did not end the span when the transaction was committed or rolled back. This caused the spans not to be collected and exported.
=> fix: add missing span.end calls for AsyncTransactionManager

google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITJsonWriteReadTest.java, google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
These were patched tests since emulator wasn't supporting these usecases. Reverting those patched tests.
=> chore: Revert patched emulator tests

samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
Update the sample tag to be consistent with other samples.
=> chore: fix tag for isolation level sample
